### ISSUE TITLE
Сross-platform smartphone/tablet app

### ISSUE THREAD

**Issue by dmitrydudkin** [lyusupov/SoftRF#101]
## Hardware

- [ ]   Standalone
- [x]   Prime Mark II
- [ ]   Uni
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

Здравствуйте,  @lyusupov!

Давно слежу за проектом и даже иногда тестирую в небе Кисловодска) Увидел в [CONTRIBUTING.md](https://github.com/lyusupov/SoftRF/blob/bde32340a27f8b412649a77573aa9da6b7a74b5e/)
то что смогу реализовать, а именно:
> create and maintain cross-platform (Flutter) smartphone/tablet app to monitor status and change settings of the following SoftRF Editions

Правда специализируюсь не на Flutter, а на React Native. 
Сделал простой прототип приложения, как альтернативу текущему web-интерфейсу. Выглядит примерно так:

![ezgif-7-2e1c47f65158](https://user-images.githubusercontent.com/7108605/98864197-90ddd800-247a-11eb-97e2-7f50421ceb96.gif) 

![ezgif-7-5b9ae17ffed5](https://user-images.githubusercontent.com/7108605/98864766-75bf9800-247b-11eb-9fd1-05bdfc45cac6.gif)

В саму прошивку пока сильно не лез, но есть задумка сразу сделать так чтобы можно было интерфейс приложения сделать динамичным, без необходимости обновления самого приложения. На устройстве достаточно будет сгенерировать json со всеми возможными настройками + текущее состояние и повесить хендлер на url типа /settings/json, а приложение уже отрисует нужный интерфейс. Думаю идея понятна.

Насколько критично использование Flutter и есть ли смысл продолжать?

**Comment by lyusupov** [comment]
Выглядит вполне прилично.

Flutter не принципиален. Обновил CONTRIBUTING.

UI для моделей с Wi-Fi не предмет для инвестиций времени на это в ближайшем будущем.
Утверждение об отдельном приложении сфокусировано не моделях, в которых нет встроенного Wi-Fi.

**Comment by dmitrydudkin** [comment]
Да, невнимательно прочитал CONTRIBUTING... А как предполагается связь с подобными устройствами? Bluetooth/USB OTG?

**Comment by lyusupov** [comment]
## Физический/канальный уровень

Андроид:
- USB Serial
- Bluetooth SPP
- 'BLE UART'

iOS:
- 'BLE UART'

Примеры использования: [1](https://github.com/lyusupov/SoftRF/wiki/Dongle-settings) , [2](https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal) , [3](https://play.google.com/store/apps/details?id=de.kai_morich.serial_bluetooth_terminal) , [4](https://github.com/kai-morich/SimpleUsbTerminal) , [5](https://github.com/kai-morich/SimpleBluetoothTerminal) , [6](https://github.com/kai-morich/SimpleBluetoothLeTerminal) 

## Сообщения

NMEA

Примеры использования: [1](https://github.com/lyusupov/SoftRF/wiki/Settings) , [2](https://github.com/lyusupov/SoftRF/blob/master/software/app/interface/SoftRF.h) , [3](https://github.com/lyusupov/SoftRF/blob/master/software/firmware/source/SkyWatch/NMEAHelper.cpp#L467)

**Comment by lyusupov** [comment]
Ticket is closed due to no further activity of the enhancement submitter.

**Resolution:** deferred

**Comment by dmitrydudkin** [comment]
@lyusupov Процесс разработки оказался дольше из-за сложностей с BLE при работе с React Native.

Вот первая тестовая [сборка](https://yadi.sk/d/nMEN10D4-dhXgQ) для Android. (на iOS также работает, но сборку не делал) Тестировал на двух устройствах Prime Mark II (других нет) через BLE и USB.  Для тестирования работы BLE включал обработку в [коде](https://github.com/lyusupov/SoftRF/blob/520ea44eb8c254f7a1cf30c05a907b6ffbf7f4fb/software/firmware/source/SoftRF/src/driver/GNSS.cpp#L1075) прошивки. 

Минимальная версия Android - 4.4, тестировал на Android 5.0.2 и Android 10.

**Comment by lyusupov** [comment]
Хорошо!

> Тестировал на двух устройствах Prime Mark II (других нет) через BLE и USB. Для тестирования работы BLE включал обработку в коде прошивки.

Всё правильно. Prime2 тоже можно управлять по проводам и BT, но по умолчанию неактивно из-за ненадобности ( через Wi-Fi удобнее ).
Для того, чтобы функцию активировать, достаточно раскомментировать [это](https://github.com/lyusupov/SoftRF/blob/master/software/firmware/source/SoftRF/src/platform/ESP32.h#L229)

Есть Андроид 5.0
Сегодня опробую.

**Comment by dmitrydudkin** [comment]
Внешний вид:
![Screenshot_20201207-135343](https://user-images.githubusercontent.com/7108605/101343196-b2bd5580-3894-11eb-8f00-38dc00751fa4.png)
![Screenshot_20201207-135600](https://user-images.githubusercontent.com/7108605/101343198-b3ee8280-3894-11eb-864f-c2f57c0b8c7e.png)
![Screenshot_20201207-135606](https://user-images.githubusercontent.com/7108605/101343203-b5b84600-3894-11eb-9759-f1e59787c52c.png)
![Screenshot_20201207-135514](https://user-images.githubusercontent.com/7108605/101343204-b650dc80-3894-11eb-9eab-48bd4cce856a.png)

> Для того, чтобы функцию активировать, достаточно раскомментировать это

Да, я включал USE_NMEA_CFG. Но без правки [в блоке условий](https://github.com/lyusupov/SoftRF/blob/520ea44eb8c254f7a1cf30c05a907b6ffbf7f4fb/software/firmware/source/SoftRF/src/driver/GNSS.cpp#L1070) не заработало. Чтение данных с BLE идет только `if !defined(USE_NMEA_CFG)` (баг?)

**Comment by lyusupov** [comment]
> Да, я включал USE_NMEA_CFG. Но без правки в блоке условий не заработало. Чтение данных с BLE идет только if !defined(USE_NMEA_CFG) (баг?)

Хм. Возможно. При случае проверю. Спасибо!

**Comment by lyusupov** [comment]
Скиньте пустое письмо на мой адрес, указанный в firmware на странице About.
Я отвечу на него с первыми результатами опробирования приложения.

**Comment by lyusupov** [comment]
Ticket is closed due to no further activity of the enhancement submitter.

**Resolution:** deferred

**Comment by dkm** [comment]
Hello @lyusupov and @dmitrydudkin 👋 I am looking for the corresponding source for the android application. Is it available somewhere?
