### ISSUE TITLE
UNI green LED does not turn on after UAT Bridge bootup. 

### ISSUE THREAD

**Issue by 8lazo8** [lyusupov/SoftRF#103]
## Hardware

- [ ]   Standalone
- [ ]   Prime Mark II
- [x]   Uni
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

![thumbnail_1608236096809](https://user-images.githubusercontent.com/17548378/102540151-eaa37480-40ae-11eb-83c9-e801aa7db988.jpg)

## Firmware version

![softrfuni](https://user-images.githubusercontent.com/17548378/102539338-d4e17f80-40ad-11eb-85a1-a61ec50d9e9b.PNG)

## Firmware settings

default

## Describe the bug (or ask a question)

After uploading the SoftRF firmware (bridge version) on LPSTK-CC1352R it boots up but the green led does not turn on. Listening on UART port it can be seen that the software is running.

The green led is functional when tested with the factory firmware.
## To Reproduce

Install and run SoftRF Uni in bridge mode (SoftRF-Bridge-v1.0-rc8-CC1352-OAD.bin bridge binary).

## Expected behavior

After bootup the green led should lit indicating that SoftRF firmware is up and running. 
https://github.com/lyusupov/SoftRF/wiki/Uni-Edition.-Firmware-maintenance-procedures   Step 11.

**Comment by lyusupov** [comment]
**Resolution:** fixed in https://github.com/lyusupov/SoftRF/commit/217b6893c5076e146ebd95c11f68aedf70311dc3
