### ISSUE TITLE
LED ring is not consistent with Alarm trigger

### ISSUE THREAD

**Issue by muravitskiy** [lyusupov/SoftRF#105]
## Hardware

- [x]   Standalone
- [ ]   Prime Mark II
- [ ]   Uni
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

![image](https://user-images.githubusercontent.com/1019142/103178959-25b45d80-4890-11eb-8be1-384bcf78df91.png)

## Firmware version

![image](https://user-images.githubusercontent.com/1019142/103178942-074e6200-4890-11eb-8152-6fd33c032a75.png)

## Firmware settings

![image](https://user-images.githubusercontent.com/1019142/103178928-f69dec00-488f-11eb-8b5a-43c5dce3003c.png)

## Describe the bug (or ask a question)

LED ring does not use a selected Alarm trigger algorithm.

## To Reproduce

2+ devices using e.g alarm trigger `distance`, `txrx_test` mode with TXRX_TEST_ALTITUDE values more than 300m difference.

## Expected behavior

Show warning according to the selected algorithm.

## Possible solution

I've created a #104 to fix this issue.

**Comment by lyusupov** [comment]
SoftRF LED ring indicates bearing (by angle) and distance (by color) of received air traffic relative to Standalone Edition own location.

**Resolution**: indavid
