### ISSUE TITLE
SoftRF Dongle Edition DSX conflict with OGN and FLARM // change of HEX-ID as prefix 0x5B is not processed

### ISSUE THREAD

**Issue by chickenhouseBjorn** [lyusupov/SoftRF#106]
## Hardware

- [ ]   Standalone
- [ ]   Prime Mark II
- [ ]   Uni
- [X]   Dongle
- [ ]   Mini
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

## Firmware version
SoftRF-firmware-v1.0-rc8-S76G.dfu

## Firmware settings
N/A

## Describe the bug (or ask a question)

I do have a SoftRF Dongle Edition flashed to current firmware, which is not visible in neither OGN nor FLARM environments, so invisible for detection units like Stratux etceteras.

As it turns out, the Dongle uses a HEX-ID for transmission starting 5B and is not processed by OGN and/or FLARM. Research and help of our fellow friends from Stratux and OGN programming revealed prefix 0x5B HEX-IDs belong to a different encoding family and were used for a service called D.S.X, so were subject to exclusion rules in receiving and processing OGN and FLARM.

SoftRF Dongle Edition therefore needs a possibility to change its HEX-ID to be something else than starting 0x5B.

## To Reproduce

just take a Dongle transmitting on a 0x5B prefix.

## Expected behavior

Visible in OGN and FLARM.

**Comment by lyusupov** [comment]
- anonymous user and
- incomplete issue report and
- works fine to me :

![image](https://user-images.githubusercontent.com/5849637/104815945-e8a51080-5828-11eb-83c7-e3c8aa28107e.png)

![image](https://user-images.githubusercontent.com/5849637/104816011-610bd180-5829-11eb-8f2f-3f3377cb4ad3.png)

<br>
<br>

**Resolution**: invalid

**Comment by lyusupov** [comment]
Reproduced with OGN software 0.2.8 
FLARM traffic is the only affected.

Every of 0x5B**** addresses have been remapped in: https://github.com/lyusupov/SoftRF/commit/f63aa9644d3af887591f346333e417c97ffed95b
