### ISSUE TITLE
Configure T-Beam NEO-M8N

### ISSUE THREAD

**Issue by vmotorkin** [lyusupov/SoftRF#109]
Hi. I use LILYGO®TTGO T-Beam NEO-M8N for topographic surveys. I need to receive NMEA messages GGA, GLL, GSA, GSV, RMC, VTG. How can I do it? Can i used u-center?
Regards.

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* anonymous user ;
* the questions are not related to the SoftRF project. Ask [LilyGO](https://github.com/Xinyuan-LilyGO/LilyGO-T-Beam) to help you.

**Resolution**: invalid.
