### ISSUE TITLE
Availability of data over Bluetooth

### ISSUE THREAD

**Issue by ljozsa** [lyusupov/SoftRF#11]
Hi,

is Bluetooth supposed to be working as of SoftRF-firmware-v1.0-rc1? When I connect to the device over Bluetooth and turn on terminal I see random crap on the screen like a baud rate on the input of the BT module was wrong. Do I need to configure HC-05 somehow before usage?

Thanks,
L.

**Comment by lyusupov** [comment]
HC-05 typically has factory default 9600 baud rate.
SoftRF is sending serial data at 38400.
Brand new HC-05 has to be reconfigured before first use with SoftRF.
One should follow HC-05 guides like this one:
https://www.itead.cc/wiki/Serial_Port_Bluetooth_Module_(Master/Slave)_:_HC-05
