### ISSUE TITLE
TTNHelper.cpp outdated, causing a few compilation errors

### ISSUE THREAD

**Issue by UniqueActive** [lyusupov/SoftRF#111]
## Hardware
- [X]   Dongle (just the TTGO T-Motion board itself)

## Describe the bug
After enabling the TTN Helper in the SoftRF.h file and filling in my IDs in the TTNHelper.cpp file, I attempted to compile the code.

First I received an error that the file "RFHelper.h" could not be found. It appears that throughout SoftRF's development it was renamed to RF.h and moved to the driver/ directory. Accordingly, I changed "RFHelper.h" to "driver/RF.h".

After fixing this, I received an error that there is no function os_runloop_once(). I renamed it to os_runloop() since that function appeared to exist and continued.

Then I am running into "undefined reference to "sx1276_receive_active". This is an external bool variable that does not appear to exist anymore either. If I just statically set it to "false" or "true", it compiles, but of course at this point I don't know if the application is doing what it is supposed to anymore.

Could you update the TTNHelper.cpp or help me with understanding the "os_runloop_once()" and "sx1276_receive_active" and how I can replace them? Thank you a lot in advance!

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* anonymous user ;
* there is no TTN in the SoftRF [Dongle Edition](https://github.com/lyusupov/SoftRF/wiki/Dongle-Edition) model description.

**Resolution**: invalid.
