### ISSUE TITLE
Compiling SoftRF for ESP32 Dev Module in Arduino IDE v1.8.13 fails

### ISSUE THREAD

**Issue by FLYINGSC0T** [lyusupov/SoftRF#112]
Followed the instructions and copied the appropriate SoftRF files to myDocuments/Arduino folder and the libraries folder to myDocuments/Arduino/libraries folder. Will not compile as files cannot be found - example:

c:\myprojects\sketch\src\platform\esp32.h:53:51: fatal error: libraries/NeoPixelBus/src/NeoPixelBus.h: No such file or directory
compilation terminated.

It would appear that the paths references are not correct or am I missing something?
Do I have to go through each and every file and change the paths for dependent files that cannot be found?

Any help please would be appreciated.

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* anonymous user ;
* [![Build Status](https://travis-ci.org/lyusupov/SoftRF.png?branch=master)](https://travis-ci.org/lyusupov/SoftRF "Build Status") 

**Resolution**: invalid.
