### ISSUE TITLE
High Load on Raspberry Pi 4

### ISSUE THREAD

**Issue by Huebenthal** [lyusupov/SoftRF#113]
While running, the SoftRF application uses almost a whole CPU core (84%) on a Raspberry Pi 4. Configuration settings make no difference. This seems to be weird if I compare the power of a RPi4 CPU with a ESP32 where the software is running as well.
By adding  usleep(1000) at the end of normal_loop() it goes down to just 5%. But I do not know how time critical the things are and whether a delay of 1ms make the things wrong.

Another issue: Removing (or commenting) #define USE_EPAPER leads to a compile error. "typedef void* EPD_Task_t;" must stay valid (outside #if defined USE_EPAPER ) to avoid.

Best regards

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* there is nothing wrong with the single core load factor . The loop was accelerated intentionally to reduce latency and improve timing accuracy of SPI and RF operations.

**Resolution**: invalid.
