### ISSUE TITLE
Barometric sensor info bug: lk8ex1 nmea sentence

### ISSUE THREAD

**Issue by balazs-h** [lyusupov/SoftRF#114]
lk8ex1 nmea sentence - is set to disabled in the firmware. 
Please set it to enable in the firmware. Or put it on Settings webui page. 
Xctrack (xcontest.org) android app reads barometric data from this NMEA sentence. 

ps:
I didnt find any information in closed issues on this topic. 

**ATTENTION** ! 

- Use this form to report bugs in released SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are allowed only when you are ready to implement them by yourself ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ ]   Prime Mark II
- [ ]   Uni
- [ ]   Dongle
- [ ]   Mini
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)

## Firmware version

<  screenshot of WebUI status page > (**required**)

## Firmware settings

<  screenshot of WebUI settings page > (**required**)

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;

**Resolution**: invalid.
