### ISSUE TITLE
Flattened battery and bricked T-Beam

### ISSUE THREAD

**Issue by freedomfpv** [lyusupov/SoftRF#117]
## Hardware

- [ ]   Standalone
- [x]   Prime Mark II
- [ ]   Uni
- [ ]   Dongle
- [ ]   Mini
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)
Unable, as has been thrown away

## Firmware version
RC-9
<  screenshot of WebUI status page > (**required*) 

## Firmware settings
Unable, as has been thrown away
<  screenshot of WebUI settings page > (**required**)

## Describe the bug
TTGO T-Beam V1.1 was accidentally left switched on for about a day, this brought the battery voltage down to 1 volt, and bricked the T-Beam. It was still recognised when plugged into a computer, but no lights came on when plugged in or a charged battery was inserted. It also did not emit a WiFi signal.

## To Reproduce
Leave a T-Beam v1.1 running on battery power with firmware version RC9

## Expected behavior
Device auto power off once a minimum voltage was reached.

**Comment by lyusupov** [comment]
* incomplete issue report ;
* anonymous user ;
* [disclaimer](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkII#disclaimer)

**Resolution**: unable to reproduce
