### ISSUE TITLE
SoftRF baud rate change

### ISSUE THREAD

**Issue by petr0808** [lyusupov/SoftRF#118]
## Hardware

- [ ]   Standalone
- [ ]   Badge
- [X]   Prime Mark II
- [ ]   Uni
- [ ]   Dongle
- [ ]   Mini
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

Firmware version
V1.0-rc8

Is it somehow possible to include a baud rate selection possibility on the web interface to be able to either change both Rx and Tx or at least Tx baud rate of the serial output? As far as I understood this setting is defined in the Softrf.h only. Defaults are: Rx: 9600 Tx: 38400. The reason is that several devices are unable to handle 38400 but instead lower baud rates.

Any feedback and proposals appreciated,
Thanks,
Peter

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* anonymous user ;
* RFEs are [not allowed](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md)

**Resolution**: invalid.
