### ISSUE TITLE
Output voltage of MT3608

### ISSUE THREAD

**Issue by ljozsa** [lyusupov/SoftRF#12]
Hi,

the output voltage of MT3608 is supposed to be set to 3.3V or 5V?

Thanks,
L.

**Comment by lyusupov** [comment]
3.3V is fine.
Although **3.5V** may give a little benefit for NRF and GNSS performance.

LEDs and BN-880 are 5V-tolerant, but ESP, NRF or RFM - are NOT.
**NE** voltage limit for ESP, NRF and SX - **3.6V**

Recommended procedure:
1) tune MT onto 3.3V first with no or little load on output pins;
2) plug everything in the shield and adjust voltage onto 3.5V under "full load".
