### ISSUE TITLE
cannot open SoftRF-firmware-v1.0-ESP32.zip

### ISSUE THREAD

**Issue by r-fairman** [lyusupov/SoftRF#122]
**ATTENTION** ! 

- Use this form to report bugs in released SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are allowed only when you are ready to implement them by yourself ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ ]   Badge
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   Bracelet
- [ ]   Uni
- [ ]   Mini
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)

## Firmware version

<  screenshot of WebUI status page > (**required**)

## Firmware settings

<  screenshot of WebUI settings page > (**required**)

## Expected behavior
Cannot open SoftRF-firmware-v1.0-ESP32.zip  and when fixed which bin file do i use to get soft rf on my Tbeam v1

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* unable to reproduce

```
$ unzip -l SoftRF-firmware-v1.0-ESP32.zip 
Archive:  SoftRF-firmware-v1.0-ESP32.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     8192  2021-03-12 15:56   boot_app0.bin
    17120  2021-03-12 15:56   bootloader_dio_80m.bin
      122  2021-10-14 12:33   firmware.txt
  1671888  2021-10-14 12:33   SoftRF.ino.bin
     3072  2021-03-12 15:54   SoftRF.ino.partitions.bin
---------                     -------
  1700394                     5 files
```

**Resolution**: invalid
