### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kaelsaes** [lyusupov/SoftRF#124]
What ist the vertical range and is it possible to change the range?

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
*  the Github 'issues' area is for true bug(s) reporting only. When you have a generic question - ask this SoftRF users [Gitter community](https://gitter.im/lyusupov/SoftRF) to help you.

**Resolution**: invalid
