### ISSUE TITLE
wrong chip id 0xafd8

### ISSUE THREAD

**Issue by kolod1am** [lyusupov/SoftRF#125]
## Hardware

- [ ]   Standalone
- [ ]   Badge
- [x]   Prime Mark II
- [ ]   Dongle
- [ ]   Bracelet
- [ ]   Uni
- [ ]   Mini
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

![20211122_145023](https://user-images.githubusercontent.com/2271248/142876397-a53a4a8d-83e4-4660-9ecc-3049e40bde70.jpg)

```
~/.local/bin/esptool.py --chip esp32 -p /dev/ttyUSB0 flash_id
esptool.py v3.2
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-D0WDQ6-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 24:0a:c4:f7:e8:80
Uploading stub...
Running stub...
Stub running...
Manufacturer: 68
Device: 4016
Detected flash size: 4MB
Hard resetting via RTS pin...
```

## Firmware version

SoftRF-firmware-v1.0.bin

## Firmware settings

Does not apply.

## Describe the bug

After writing SoftRF to the board, no WiFi SSID appears, no bluetooth device can be scanned. No wonder, as reading from ttyUSB0 gains:
```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
wrong chip id 0xafd8
wrong chip id 0xafd8
wrong chip id 0xafd8
wrong chip id 0xafd8
wrong chip id 0xafd8
wrong chip id 0xafd8
wrong chip id 0xafd8
wrong ch�ets Jul 29 2019 12:21:46
```
and running.

The board came with Meshtastic. It boots and the bluetooth device appears in smartphone. So I know that the board is operational. I wonder where message "wrong chip id" comes from as I cannot find it in SoftRF source code nor in the binary.

## To Reproduce
~/.local/bin/esptool.py --chip esp32 -p /dev/ttyUSB0  write_flash 0x00000 ESP32/SoftRF-firmware-v1.0.bin

This is what esptool reported:
```
~/.local/bin/esptool.py --chip esp32 -p /dev/ttyUSB0  write_flash 0x00000 ESP32/SoftRF-firmware-v1.0.bin
flash 0x00000 ESP32/SoftRF-firmware-v1.0.bin
esptool.py v3.2
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-D0WDQ6-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 24:0a:c4:f7:e8:80
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00000000 to 0x00085fff...
Compressed 548672 bytes to 394555...
Wrote 548672 bytes (394555 compressed) at 0x00000000 in 34.8 seconds (effective 126.0 kbit/s)...
Hash of data verified.
```

## Expected behavior
SoftRF boots to operational state.

**Comment by lyusupov** [comment]
Reporter is trying to flash **ESP32** SoC with firmware binary been built for **ESP8266** SoC.
* [ESP32 binaries location](https://github.com/lyusupov/SoftRF/tree/master/software/firmware/binaries/ESP32/SoftRF)
* [ESP32 firmware installation instructions](https://github.com/lyusupov/SoftRF/blob/master/software/firmware/binaries/README.md#esp32)

**Resolution:** invalid

**Comment by kolod1am** [comment]
Many thanks for your guidance. I have got ESP32 binary from [ESP32 binaries location](https://github.com/lyusupov/SoftRF/tree/master/software/firmware/binaries/ESP32/SoftRF), unzipped the archive and did separate esptool write_flash command for each line in firmware.txt. In my case it was:
```
~/.local/bin/esptool.py --chip esp32 -p /dev/ttyUSB0  write_flash 0xe000  boot_app0.bin
~/.local/bin/esptool.py --chip esp32 -p /dev/ttyUSB0  write_flash 0x1000  bootloader_dio_80m.bin
~/.local/bin/esptool.py --chip esp32 -p /dev/ttyUSB0  write_flash 0x8000  SoftRF.ino.partitions.bin
~/.local/bin/esptool.py --chip esp32 -p /dev/ttyUSB0  write_flash 0x10000 SoftRF.ino.bin
```

Now SoftRF is up and running. I can see its WiFi ESSID.
