### ISSUE TITLE
Very fast battery drain when powered off - LilyGO® T-Echo Badge Version

### ISSUE THREAD

**Issue by b8fly** [lyusupov/SoftRF#126]
**ATTENTION** ! 

- Use this form to report bugs in released SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are allowed only when you are ready to implement them by yourself ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [x]   Badge
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   Bracelet
- [ ]   Uni
- [ ]   Mini
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

![IMG_2618](https://user-images.githubusercontent.com/1789345/143248603-02c8b0c7-5b8f-49d6-a142-37095b1d7f53.jpg)

## Firmware version

![Screenshot_2021-11-24-14-41-47](https://user-images.githubusercontent.com/1789345/143257117-cbc9c0d0-cd67-4d41-8e2c-8fe3ec7500d1.png)

## Firmware settings

![Screenshot_2021-11-24-15-06-56](https://user-images.githubusercontent.com/1789345/143256022-bb945a77-fef2-4990-a40f-1eae5073d6aa.png)
![Screenshot_2021-11-24-15-07-05](https://user-images.githubusercontent.com/1789345/143256042-2345d2c8-da4d-4140-910a-8090476fe658.png)

## Describe the bug
When powered off (Normal Off Screen) the T-Echo completely drains battery very fast (in days).
(Is this normal and expected behavior? If I do not use the fully charged device for a few days the battery is drained totally and I have first to recharge it before use.)

## To Reproduce
Fully charge the device. Shut off and wait a few days.

## Expected behavior
With a sleep current as documented of 0.25mA the expected discharging time of the powered off device should be around 140 days (850mAh battery). So the drawn current of the device seems to be much higher (maybe around 5mA did not measure it precisely).

**Comment by lyusupov** [comment]
Inspect, if this resistor is soldered on your particular T-Echo board.

![](https://user-images.githubusercontent.com/5849637/143762754-b83c82ed-a246-4afd-93ae-4b70cb25bfa3.jpg)

**Comment by b8fly** [comment]
Thanks for coming back to me. On my T-Echo board there seems to be no such resistor..
![IMG_2624](https://user-images.githubusercontent.com/1789345/143763573-a3fb6ad8-1796-4f3a-afa5-e3f370aabaf6.jpg)
.

**Comment by lyusupov** [comment]
Your board has Rw missing but R37 is installed.

![TE-3V3_EN](https://user-images.githubusercontent.com/5849637/143763796-4a75679f-5275-4b60-80ad-c5cf0e1f8f61.png)

You can try to fix your issue with soldering a 'bridge' over Rw pads.

**Comment by b8fly** [comment]
Thank you for your research.
A normal bridge (simple wire - no resistor) will solve the problem? Did I understand that correctly? I don't know if I can do this without destroying the board. 
I will probably simply put a switch between the battery and the board.
Thanks again for solving the problem an keep up the great work!

**Comment by lyusupov** [comment]
T-Echo with Zetta Device ZD25WQ16B flash memory chip are the only affected.

**Resolution:** fixed

T-Echo firmware binaries were updated in this commit: https://github.com/lyusupov/SoftRF/commit/97fe84ade91bdd47c4ef62efd31fb4731fe61832
