### ISSUE TITLE
Is TTGO T-motion  still supported?

### ISSUE THREAD

**Issue by FPSychotic** [lyusupov/SoftRF#127]
I cannot find it in the documents, so not sure if it is not supported by this repo nevermore.

Cheers.

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* anonymous user ;
*  the Github 'issues' area is for true bug(s) reporting only. When you have a generic question - ask this SoftRF users [Gitter community](https://gitter.im/lyusupov/SoftRF) to help you.

**Resolution**: invalid
