### ISSUE TITLE
The displayed temperature is 5 degrees higher than the actual temperature.

### ISSUE THREAD

**Issue by darton** [lyusupov/SoftRF#128]
## Hardware
- [x ]   Prime Mark II

## Firmware version
1.0 EU

## Describe the bug
The displayed temperature is 5 degrees  higher than the actual temperature.

## To Reproduce
Connect BME280 sensor module.

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* [**Prime Mark II**](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkII) does not have BME280 sensor .

**Resolution**: invalid
