### ISSUE TITLE
SOftRF-Dongle T-Motion Board I2C not working

### ISSUE THREAD

**Issue by drucknase** [lyusupov/SoftRF#129]
## Hardware

- [ ]   Standalone
- [ ]   Badge
- [ ]   Prime Mark II
- [x ]   Dongle
- [ ]   Bracelet
- [ ]   Uni
- [ ]   Mini
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

![T-Motion_HW_web](https://user-images.githubusercontent.com/41738752/155329761-c623e418-1cb7-410f-8304-43e165ae6a67.jpg)

## Firmware version

own test firmware

## Describe the bug
I use PlatformIO as development platform. I can upload firmware, tried with a Blink-sketch. Developed own firmware for a TTN-Tracker which works fine including the GNSS part. I tried to connect a OLED to the I2C bus on PB7 and PB6 using Wire-Library but no signal on the two pins. Studied your sketches and found that you use Wire-Lib too.

Wrote a test-sketch which use digitalWrite to PB6 and PB7 to see if I can generate some clock like signals and this works perfekt. So the port is not damaged.

But there are no I2C CLK or I2C SDA signals when I use Wire.begin(I2C_SDA,I2C_SCL) and Wire.beginTransmission(adr). Measured with an analyser.

I feel like hw pins are not mapped correct for the AS76G ASIC. Is there any trick to get I2C working?

Thanks!

**Comment by lyusupov** [comment]
* **report has nothing to do with SoftRF** firmware ( [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ) ;
* anonymous user. 

**Resolution:** invalid
