### ISSUE TITLE
enhancement: beacon hopping over different protocols 

### ISSUE THREAD

**Issue by qubolino** [lyusupov/SoftRF#130]
i’d like to be able to send beacons over different protocols in order to be seen by different devices during my flight (at least flarm and ogn). 
i don’t think it’s too difficult to implement and with proper guidance i’m happy to do it.

**Comment by lyusupov** [comment]
* anonymous user ;
* [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) ;
* [Combined use of multiple SoftRF units](https://github.com/lyusupov/SoftRF/wiki/Combined-use-of-multiple-SoftRF-units)

** Resolution**: invalid

**Comment by qubolino** [comment]
🙄
