### ISSUE TITLE
Augmenting ForeFlight weather?

### ISSUE THREAD

**Issue by DGaffney** [lyusupov/SoftRF#133]
Hey all- I’m interested in what few details I know about this technology to try proof of converting a way to augment weather data coming into ForeFlight with a Lora radio. Obviously that’s a long way off but the first step in principle would be receiving data in air as raw packets. If my understanding is correct, you could in principle piggy back off the helium network to exchange these messages (though I’m not sure how the antennas in that network spread their signal, and they may just not reach upwards?) if I wanted to experiment with this project, what hardware, software, and documentation would serve as the best starting point? For context I’m a 15 year backend dev with some arduino and lots of pi experience but less with more physical engineering like this - I mostly am always just using http.

**Comment by lyusupov** [comment]
*  the Github 'issues' area is for true bug(s) reporting only. When you have a generic question - ask this SoftRF users [Gitter community](https://gitter.im/lyusupov/SoftRF) to help you ;
* [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) ;
* there were few projects to transmit aviation weather over ISM band radio. One of them was driven (_and abandoned later_) by Stratux team: https://github.com/stratux/txwx ,  http://www.avcanada.ca/forums2/viewtopic.php?t=130728
    Good luck to you if you gonna follow this (_or any other_) way.

**Resolution**: invalid
