### ISSUE TITLE
SoftRF Tool.No device recognition with several serial usb devices connected

### ISSUE THREAD

**Issue by XCNav** [lyusupov/SoftRF#134]
**ATTENTION** ! 

- Use this form to report bugs in released SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are allowed only when you are ready to implement them by yourself ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ ]   Badge
- [ ]   Prime Mark II
- [x]   Dongle
- [ ]   Bracelet
- [ ]   Uni
- [ ]   Mini
- [ ]   Academy
- [ ]   Lego
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)
![20220706_125419](https://user-images.githubusercontent.com/78668199/188012221-ddd5c50c-3217-4203-8f0d-2c0744742433.jpg)

## Firmware version
1.0
<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) status page > (**required**)

## Firmware settings

<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) settings page > (**required**)
Device is build in, can not connect.
## Describe the bug

Our XCNAV Edition has 2 build in FT232 serial to usb connverter. When I Plug the the dongle version in and try to configure it, the softRF toolmconnects to the FT232 instead of the dongle

## To Reproduce
Take an Android device and connect different serial devices via USB. At last plug the dongle and try ro connect via SoftRf Tool.

## Expected behavior
If SoftRf Tool recognizes more than one device make the devices visible and  selectable by the user.

**Comment by lyusupov** [comment]
* anonymous user ;
* the [**SoftRF Tool**](https://play.google.com/store/apps/details?id=com.dda.softrftool) is a third-party app which has nothing to do with this SoftRF GitHub repo. Ask for support (if any) on the [app's home page](https://play.google.com/store/apps/details?id=com.dda.softrftool) in Google Play ;
* read the [**Disclaimer**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool#disclaimer) 
![image](https://user-images.githubusercontent.com/5849637/188066210-d664eb39-2fd7-415c-8bf6-0eba68796453.png)

**Resolution:** invalid
