### ISSUE TITLE
how to get ADSB + OGN + Flarm - which soft and hardware?

### ISSUE THREAD

**Issue by git-78** [lyusupov/SoftRF#137]
Hi,

Thank you a lot to all dev and @lyusupov for SoftRF and its docs! Yet, I have read and re-read the doc on SoftRF (plus dump1090 and flare), and I feel lost on how to achieve my objectives. I would really appreciate if one could lead me in the right direction...

My goal is to receive both ADS-B, OGN and Flarm traffic on a computer not connected to Internet (a mini-PC running Debian or Ubuntu server, preferably not a raspberry). I initially thought to use two Rtl-sdr usb keys, possibly some Nooelec, one for ADSB with dump1090 (that's the easy part) and the other for OGN and Flarm - and it's where I'm lost.

1. If I were using the dongle version of SoftRF:
    1. Did I understand correctly that I would need two dongles, one for OGN, one for Flarm? Is that correct?
    2. Could I redirect both OGN and Flarm flows through dump1090 ? I think I read somewhere that I could pipe the stream and send it by netcat to dump1090, but I'm not sure 1) of the commands, 2) if dump1090 could accept two incoming flows.
2. If I choose to use a Rtl-Sdr:
    1. Can I use one single Rtl-Sdr for both OGN and Flarm?
    2. Which software could I use? Can SoftRF be used for that and how? Or should I use Flare (https://github.com/lyusupov/flare/) ? With Flare, I was thinking to pipe the output of `rtl_sdr -f 868.05m -s 1.6m` to both `nrf905_demod 29 | ./flarm_decode` and also `ogntp_demod 29 | ./ogntp_decode` - but is that a good idea? Flare seems to be not maintained anymore
    3. If I'm not wrong, Rtl-Sdr is said to have a better range than LilyGO's T-Motion, can anyone confirm? Is that significant?
4. If I'm not wrong, whatever the solution, we need a GPS when receiving Flarm. Why? Is that obligatory?

Thank you again for your help, I really appreciate! Please don't hesitate to correct me if what I understood was wrong or not a good idea.

**Comment by lyusupov** [comment]
*  the Github 'issues' area is for true bug(s) reporting only. When you have a generic question - ask this SoftRF users [Gitter community](https://gitter.im/lyusupov/SoftRF) to help you ;
* anonymous user ;

**Resolution**: invalid
