### ISSUE TITLE
Wrong WiFi Password Prime Edition MkII

### ISSUE THREAD

**Issue by jhonny001** [lyusupov/SoftRF#140]
## Hardware

- [ ]   Standalone
- [ ]   Badge
- [X]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Uni
- [ ]   Mini
- [ ]   Bracelet
- [ ]   Academy
- [ ]   Lego
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   UAT978 module
- [ ]   Flight Recorder

![WhatsApp Image 2023-02-27 at 09 49 35-min](https://user-images.githubusercontent.com/6034135/221518019-54398ce7-21be-4157-9a23-8911f9d49bb8.jpeg)

## Firmware version

[SoftRF-firmware-v1.2-ESP32] (I can't log in to show a SoftRF screenshot neither the LCD is working)

## Firmware settings

Stock settings. This is a fresh install on a new board. I can't provide a screenshot as I have no access to WiFi or BT.

## Describe the bug
The WiFi password is reported to be incorrect. (Password "12345678"). I tried from different devices (2 Android and one Windows laptop) the three of them reported password is incorrect.

## To Reproduce
Fresh install in LILYGO board TTGO T-BEAM V11 with SX1262 and M8N GPS module. FW SoftRF-firmware-v1.2-ESP32.  Try to connect using WiFi. 

## Expected behavior
Connect to the WiFi hotspot to configure.

**Comment by lyusupov** [comment]
* [Disclaimer](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkII#disclaimer)

**Resolution**: unable to reproduce

**Comment by lyusupov** [comment]
https://groups.google.com/g/openglidernetwork/c/G2kAqVuqpKg

<img width="704" alt="image" src="https://user-images.githubusercontent.com/5849637/221532604-9d5b70e3-314a-4a1c-af8b-b0ca4df937d5.png">


<img width="689" alt="image" src="https://user-images.githubusercontent.com/5849637/221532465-c2d50a3f-f371-4969-9096-7b08e3f0600d.png">

**Comment by jhonny001** [comment]
Hi Linar, thank you very much for the support. Could you please grant me access to the Google Groups thread so I can check how Doug fixed the issue? Cheers,
