### ISSUE TITLE
SoftRF tool is unavailable for android 12 in google play

### ISSUE THREAD

**Issue by RE-Specto** [lyusupov/SoftRF#141]
just tried to download the softRF tool from google play, received a message stating that:  
`this app isn't available for your device because it was made for an older version of Android`  
device is Galaxy note 10+ SM-N976B Android 12

![softrf](https://user-images.githubusercontent.com/58845427/232331599-9b125dea-0c23-42f9-99ef-9ffbd1060e7c.png)

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template]  ;
* the [**SoftRF Tool**](https://play.google.com/store/apps/details?id=com.dda.softrftool) is a third-party app which has nothing to do with this SoftRF GitHub repo. Ask for support (if any) on the [app's home page](https://play.google.com/store/apps/details?id=com.dda.softrftool) in Google Play ;
* read the [**Disclaimer**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool#disclaimer) 
![image](https://user-images.githubusercontent.com/5849637/188066210-d664eb39-2fd7-415c-8bf6-0eba68796453.png)

**Resolution:** invalid
