### ISSUE TITLE
Baud Rate of SoftRF Serial Output is not documented

### ISSUE THREAD

**Issue by BrownGraham** [lyusupov/SoftRF#144]
**ATTENTION** ! 

- Use this form to report bugs in an [**Official Release**](https://github.com/lyusupov/SoftRF/releases) of SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are only allowed when you are ready to implement them by yourself. See [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) list for details ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ ]   Badge
- [X ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Uni
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

![IMG-8861](https://github.com/lyusupov/SoftRF/assets/8800312/8101d737-fb06-45bc-8994-6029827b916f)

## Firmware version

<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) status page > (**required**)

## Firmware settings
![IMG-8862](https://github.com/lyusupov/SoftRF/assets/8800312/bc80990d-0197-4440-9331-32aad1b8bcff)
![IMG-8863](https://github.com/lyusupov/SoftRF/assets/8800312/be9baee2-1e2a-4fb7-b3b3-1f7273af0c00)
![IMG-8860](https://github.com/lyusupov/SoftRF/assets/8800312/b9d4faa7-f3cc-409f-83bd-2274429806b5)
![IMG-8864](https://github.com/lyusupov/SoftRF/assets/8800312/ff67b29c-fc70-45f8-87ae-0eb54254e20f)

## Describe the bug
The output baud rate of the serial connection of the SoftRF software is not documented on the SkyView EZ wiki page (https://github.com/lyusupov/SoftRF/wiki/SkyView-EZ)

## To Reproduce
Review documentation of the SkyView EZ wiki page (https://github.com/lyusupov/SoftRF/wiki/SkyView-EZ)

## Expected behavior
Documented for set up of SkyView EZ with a serial connection to a Prime Mark II device.

**Comment by lyusupov** [comment]
![image](https://github.com/lyusupov/SoftRF/assets/5849637/179f4b46-2f98-413a-a735-955c025896d1)

<br>

We don't care about 'aftermarket' firmware binaries built by someone else

<br>

![image](https://github.com/lyusupov/SoftRF/assets/5849637/d77ade60-dc5d-4beb-ad64-3cee75ba5efc)

<br>

Ask for support to those individuals you've taken the firmware from.

<br>

**Resolution:** invalid
