### ISSUE TITLE
GNSS not responding on commands or send NMEA sentences

### ISSUE THREAD

**Issue by drucknase** [lyusupov/SoftRF#146]
## Hardware

- [ ]   Standalone
- [ ]   Badge
- [ ]   Prime Mark II
- [x]   Dongle
- [ ]   SkyView EZ
- [ ]   Uni
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

![Picture_T-Motion_No5_230829_web](https://github.com/lyusupov/SoftRF/assets/41738752/0ffd26d6-3fd1-4d4c-9aa9-063c9bec54f7)

## Firmware version

`SoftRF-STM32 FW.REV: 1.3 DEV.ID: 3a4e074c
Copyright (C) 2015-2023 Linar Yusupov. All rights reserved.

Reset reason: 6
EXT_SYS
Free heap size: 6276
No reset information available

WARNING! User defined settings are not initialized yet. Loading defaults...
SX127x RFIC is detected.
WARNING! Barometric pressure sensor is NOT detected.

TTGO T-Motion (S76G) Power-on Self Test

Built-in components:
RADIO   : PASS
CLK SRC : TCXO
GNSS    : FAIL

External components:
DISPLAY : N/A
BMx280  : N/A

Power-on Self Test is complete.

Data output device(s):
NMEA   - USB CDC
GDL90  - NULL
D1090  - NULL

$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,34*44
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,34*44
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,34*44
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,34*44
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,34*44
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,34*44
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,34*44
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,34*44
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,34*44
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,37*47
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,37*47
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,37*47
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,37*47
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,37*47
$PFLAU,0,0,0,1,0,,0,,,*4F
$PSRFH,4E074C,1,0,0,34*44
$PFLAU,0,0,0,1,0,,0,,,*4F
`

## Firmware settings

just after flashing software (**required**)

## Describe the bug
the GNSS does not respond to commands. I tried also with own software, so after sending a command via serial interface, the GNSS chip (CXD5603) dows not respond. No NMEA output. Only 1 sec impuls can be observed on PB5.
Didn't find the same problem in the closed issues

## To Reproduce
I have two out of five T-Motion boards which show the same behavior. 

## Expected behavior
get respond from GNSS chip including NMEA sentences

**Comment by lyusupov** [comment]
* anonymous user
* your boot log contains the following message:

```
Built-in components:
RADIO : PASS
CLK SRC : TCXO
GNSS : FAIL
```

which is clear indication that your GNSS issue has nothing to do with the **SoftRF** firmware.
Read the [**Disclaimer**](https://github.com/lyusupov/SoftRF/wiki/Dongle-Edition#disclaimer) against hardware issues then go work with your seller / supplier.

**Resolution**: invalid
