### ISSUE TITLE
Ham Edition Firmware Download

### ISSUE THREAD

**Issue by TechMindsYT** [lyusupov/SoftRF#147]
Hi, sorry for posting here, but I have a quick question.

I have a TWR Plus, VHF, I have Ham License and am looking for the Ham Edition firmware so I can try out APRS. I would like to make a video about this great software, but I just cannot locate the firmware for the Ham Edition. Please could someone link me?
Thanks
Matt
Tech Minds

**Comment by lyusupov** [comment]
![](https://github.com/lyusupov/SoftRF/assets/5849637/6a3dbfef-9ebb-4d4d-ad8f-0d666d05481c)

**Resolution**: invalid
