### ISSUE TITLE
SkyView firmware update 0.13-ESP32 fail

### ISSUE THREAD

**Issue by DocTopi** [lyusupov/SoftRF#148]
Hardware:

SkyView EZ on e-Paper TTGO T5S with Software Version 0.12 ESP32

Firmware update via "Web method" with "SkyView_C209.ino.bin" crashes at 55%.

Firmware update via ESP flash download tool v3.9.5 and "SkyView_C209.ino.bin" finished, but thereafter Connection type "WiFi UDP" is missing ???

Was "SkyView_C209.ino.bin" the wrong "ino.bin"?

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* anonymous user

**Resolution**: invalid
