### ISSUE TITLE
Broken iGates recommended for Ham-Edition

### ISSUE THREAD

**Issue by hessu** [lyusupov/SoftRF#149]
Hi,

The Ham-Edition wiki page recommends two broken iGate packages for receivers:

https://github.com/lyusupov/SoftRF/wiki/Ham-Edition#pypacket
https://github.com/lyusupov/SoftRF/wiki/Ham-Edition#ionosphere

Both of these are based on decoding multimon-ng, which by design has human-readable output and will corrupt packets with non-printable characters, and will handle multiline packets incorrectly as well. These igates should not be used anywhere on the APRS networks, and should not be recommended until these issues are fixed. For RTL-SDR use, better iGates can be configured with rtl_fm -demodulated audio being fed into the Direwolf modem software, which in turn provides a binary clean KISS interface for igate software, and can also act as a standalone igate.

https://github.com/cceremuga/pypacket/issues/119
https://github.com/cceremuga/ionosphere/issues/30

**Comment by lyusupov** [comment]
**PyPacket** and **IonoSphere** have been replaced by **Dire Wolf**:
https://github.com/lyusupov/SoftRF/wiki/Ham-Edition#dire-wolf
