### ISSUE TITLE
Android 12/

### ISSUE THREAD

**Issue by cdeerinck** [lyusupov/SoftRF#150]
Just bought an Android phone so I can config a Badge addition.  The Google play store says this App is not compatible with Android 12.  Are there any plans to make that work?

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* duplicates  #141
* the app is known to work nicely from Androd 5 to Android 13

**Resolution:** duplicate
