### ISSUE TITLE
SkyView losing GLD90 connection to Stratux and hanging

### ISSUE THREAD

**Issue by Puppa-Smurf** [lyusupov/SoftRF#151]
1.	I have check and no there is not a mention in the issues log.
2.	Hardware SkyView EZ
3.	Firmware version 0.13
4.	Firmware settings Picture provided
![IMG_20231224_131650](https://github.com/lyusupov/SoftRF/assets/127368954/4afaac36-f3af-4951-8408-7f7a14b4556e)

5.
![Screenshot_2023-12-24-13-18-20-691](https://github.com/lyusupov/SoftRF/assets/127368954/c6e23a02-913a-4f90-b325-5afee601ef0f)
![Screenshot_2023-12-24-13-18-27-142](https://github.com/lyusupov/SoftRF/assets/127368954/8f87d261-bfaa-450b-981f-027f56c65b95)
![Screenshot_2023-12-24-13-19-31-042](https://github.com/lyusupov/SoftRF/assets/127368954/1425aab9-36c2-4ad0-84b5-4eb83daeacdf)
	Stratux stratux-v1.6r1 and latest version
6.	Hardware Raspberry Pi4B

## Describe the bug:
I have been working on the Skyview for a number of days and have some observations that may be of interest to the developer

 I am running a Pi4 with the latest 64bit RasPiOS Lite Bullseye Image (As selected from the Pi imager, and onto that installed  https://github.com/VirusPilot/stratux-pi4 (standard build ). As per the instructions. All fired up and working with access via AP and Client networks.

Then obtained the hardware - TTGO T5S board and followed your install instructions  [https://github.com/lyusupov/SoftRF/wiki/SkyView-EZ for the firmware 0.13](https://github.com/lyusupov/SoftRF/wiki/SkyView-EZ%20for%20the%20firmware%200.13)

Issues:
I tried both SkyView_C105.ino.bin & SkyView_C209.ino.bin, but could not get it to work on WIFI! I 

Then while testing from a hard reboot, every now and then with the board rate set to 19200, it would connect for a few seconds, flash up on the screen in Nav_box_1 a number, and in Nav_Box_2 “GDL” then drop back to UNK. The Webui would then say no connection.

My guess was serial speed was the issue, so and ended up trying multiply combinations of the settings of GDL90 such as setting the board rate across the whole range. I could see on the TTGO board Webui that is was connected WIFI, but would not see the GDL90 stream.

I then rebuilt the TTGO a number of times and regressed the build versions all the way down with the same result.

I could see that I had a firm IP connection, and could ping the TTGO, but would not get a stable stream connection ☹

The went back to an old Stratux image I had stratux-v1.6r1-eu027-3d07b461.img, and fired it up.
And confirmed that it was working correctly and had it set as AP+Client so I was linked to it from my PC. All working as expected.

Reset up the TTGO with v0.12 and it connected via WIFI, then when I set it to GDL, it would not work until I set the connection rate to Maximum(200000) This would work most of the time, but would hang after a hour or so ☹ requiring a hard reboot of the TTGO. If I had the system set to Imperial it would hang after a few seconds. 

It will have 0 Aircraft and data UNK with NO DATA across the screen, with the power every now and then changing from 4.2 to 4.1 (So the screen is alive) and only a hard reboot with bring it back to life ☹

To Reproduce:
On this configuration, just turn it on ☹ and wait.

Expected behaviour:
To maintain connection to the data source without coming up with UNK, and requiring a hard reset to get GDL back in Nav_Box_2.

Notes: I will be testing with a Skyecho2 in a few weeks to see if this is any better, but suspect it’s the Skyview end ☹ 

Additional:

Yes I know it’s a request 😉 
As a parting comment, and as the 20Km setting {zoom_high) it would be very helpful to increase this as the 20KM is the diameter with the inner circle only at 10Kms that’s only 5.39957 NMs which is a little bit of an issue.

**Comment by lyusupov** [comment]
We don't use SkyView EZ with Stratux and unlikely gonna do it in the future,

<img width="657" alt="image" src="https://github.com/lyusupov/SoftRF/assets/5849637/8aa1b3b0-c968-48c3-bc65-b841a65ef698">

Fix the issue (if any) by yourself then let us know how you did that,


**Resolution**: unable to reproduce.
