### ISSUE TITLE
Aircraft database not loaded for Badge edition.

### ISSUE THREAD

**Issue by primaldev** [lyusupov/SoftRF#155]
**ATTENTION** ! 

- Use this form to report bugs in an [**Official Release**](https://github.com/lyusupov/SoftRF/releases) of SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are only allowed when you are ready to implement them by yourself. See [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) list for details ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [X]   Badge
- [ ]   Prime Mark III
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   SkyView Pico
- [ ]   Uni
- [ ]   Ham
- [ ]   Midi
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

Lilygo t-echo edition.

## Firmware version
1.4

## Describe the bug
If you used a previous version of the firmware, or not using the settings.json, ui->adb will not be set and neither of these functions are executed, resulting the file not to be loaded
File: nRF52.cpp
![Screenshot from 2024-02-13 13-31-49](https://github.com/lyusupov/SoftRF/assets/8418391/f1c110d0-9c34-4134-ab5a-9c2c9fd61a2e)

## To Reproduce
Upgrade from a previous version and then add the Aircrafts file ogn.cbd. It will not be loaded. For testing I added
 ui->adb = DB_OGN; 
above the line and then it works.
## Expected behavior
The value ui->adb should be set to a default value if it's invalid or null. Or a settings.json, pre-config step requirement should be added.

**Comment by lyusupov** [comment]
* **required** [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) **sections** are incomplete

**Resolution:** invalid
