### ISSUE TITLE
No Aircrafts data

### ISSUE THREAD

**Issue by dingetje** [lyusupov/SoftRF#156]
**ATTENTION** ! 

- Use this form to report bugs in an [**Official Release**](https://github.com/lyusupov/SoftRF/releases) of SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are only allowed when you are ready to implement them by yourself. See [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) list for details ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ x]   Badge
- [ ]   Prime Mark III
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   SkyView Pico
- [ ]   Uni
- [ ]   Ham
- [ ]   Midi
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)
![2024-03-08 14 43 19](https://github.com/lyusupov/SoftRF/assets/609871/5ae485ff-bedf-4153-b3a5-d6eddce8bf29)

## Firmware version

<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) status page > (**required**)
![2024-03-08 14 37 40](https://github.com/lyusupov/SoftRF/assets/609871/d13a96c5-8c49-43ee-b1d9-906e90e1710d)

## Firmware settings

<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) settings page > (**required**)
![2024-03-08 14 38 06](https://github.com/lyusupov/SoftRF/assets/609871/3910a5e8-bd48-4643-ae88-e7ec032c28f2)

## Describe the bug

After updating to latest SoftRF version and uploading the latest OGN database following the instructions in the Wiki, the result is that a warning message shows "NO AIRCRAFTS DATA"

## To Reproduce
Upgrade from an older SoftRF version to the latest release

## Expected behavior
Aircrafts data loaded

**Comment by dingetje** [comment]
Also reported in https://github.com/lyusupov/SoftRF/issues/155 but closed as invalid because not following template. Root cause analysis done in that ticket though.

**Comment by dingetje** [comment]
Known issue:

Badge may lose OGN aircraft data setting when upgraded from [Release 1.3](https://github.com/lyusupov/SoftRF/releases/tag/1.3). Use [SoftRF on-line UI tool](http://soaringweather.no-ip.info/SoftRF/ui.html) to apply 'GliderNet' setting manually 

Very unclear instructions, here's how to fix:

- follow the link to the SoftRF on-line UIT tool
- change settings to your likings
- copy the resulting NMEA control sentence, starts with $PSKVC
- make sure Badge is powered on
- click on the [Web Bluetooth LE Terminal](https://loginov-rocks.github.io/Web-Bluetooth-Terminal/)
- bind to your SoftRF Badge
- when connected, paste the NMEA sentence in the "Type something to send..." input line near the bottom of the screen
- Badge will reboot
- Issue resolved

**Comment by lyusupov** [comment]
Duplicates '**Known issues**' section of [**Release 1.4 Notes**](https://github.com/lyusupov/SoftRF/releases/tag/1.4)

**Resolution:** duplicate

This is no longer an issue after this commit: https://github.com/lyusupov/SoftRF/commit/5aa90af915349b8fb8af8da4db94a6ee0ea969ac
