### ISSUE TITLE
Bad aircraft data

### ISSUE THREAD

**Issue by clydebarrow** [lyusupov/SoftRF#157]
**ATTENTION** ! 

- Use this form to report bugs in an [**Official Release**](https://github.com/lyusupov/SoftRF/releases) of SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are only allowed when you are ready to implement them by yourself. See [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) list for details ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [x]   Badge
- [ ]   Prime Mark III
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   SkyView Pico
- [ ]   Uni
- [ ]   Ham
- [ ]   Midi
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)
![20240330_181125](https://github.com/lyusupov/SoftRF/assets/2366188/3fead0cb-21fc-4940-919c-a07b975919d9)

## Firmware version

1.4 installed from Releases page via UF2.

<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) status page > (**required**)
![Screenshot_20240330-171806](https://github.com/lyusupov/SoftRF/assets/2366188/08a92b9f-147b-4220-9049-2aa130259a17)

## Firmware settings

<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) settings page > (**required**)
![Screenshot_20240330-171609](https://github.com/lyusupov/SoftRF/assets/2366188/e8bd2d31-66a0-49fd-bd3c-c5f5e0623966)

## Describe the bug

Until recently this was inter-operating well with Flarm devices, using the Legacy protocol. Now it receives data, but the reported aircraft data is completely bogus. The distance is impossibly large, and the aircraft type changes randomly.

GPS data received via Bluetooth is correct so the device does have a valid GPS location.

The same behaviour was observed with firmware 1.3, updating did not change this.

## To Reproduce

Receive Flarm transmissions with the T-Echo SoftRF model.

## Expected behavior

Reported data will be valid.

**Comment by lyusupov** [comment]
- "Enhancements" of existing features are only allowed when you are ready to implement them by yourself. See [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) list for details ;

<br>
<br>

<img width="796" alt="contr" src="https://github.com/lyusupov/SoftRF/assets/5849637/5a437e75-c1f2-4f80-b960-5b3ff884d2ce">

<br>
<br>

**Resolution:** invalid

**Comment by clydebarrow** [comment]
I was aware that feature requests were not welcome here, but perhaps you could explain more why this would be considered an enhancement. What information am I missing? Has there been a change in the Flarm protocol recently that renders SoftRF incompatible?

**Comment by lyusupov** [comment]
https://groups.google.com/g/openglidernetwork/c/WLVx0q3PSzc

**Comment by lyusupov** [comment]
Volunteer contributors are welcome: https://pastebin.com/YB1ppAbt

[![Join the chat at https://gitter.im/lyusupov/SoftRF](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/lyusupov/SoftRF?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by lyusupov** [comment]
[![Release](https://img.shields.io/github/v/release/lyusupov/SoftRF)](https://github.com/lyusupov/SoftRF/releases/tag/1.5.1)
