### ISSUE TITLE
SoftRF UAV edition on ExpressLRS 900mhz receiver. 

### ISSUE THREAD

**Issue by geofrancis** [lyusupov/SoftRF#158]
I have recently got back into flying and have been looking to build a SoftRF UAV module again but for a smaller 250g plane and when i was shopping for parts it occurs to me that softrf uav is essentially the same hardware as a ExpressLRS 900mz receiver, 

![Screenshot 2024-04-11 175026](https://github.com/lyusupov/SoftRF/assets/5570278/15655ade-16c2-4e67-ad16-57d94253ba6b)

this is the pinout for a generic 900mhz recevier 

https://github.com/ExpressLRS/targets/blob/master/RX/Generic%20900.json

> {
    "serial_rx": 3,
    "serial_tx": 1,
    "radio_dio0": 4,
    "radio_dio1": 5,
    "radio_miso": 12,
    "radio_mosi": 13,
    "radio_nss": 15,
    "radio_rst": 2,
    "radio_sck": 14,
    "power_min": 0,
    "power_high": 2,
    "power_max": 2,
    "power_default": 2,
    "power_control": 0,
    "power_values": [120,124,127],
    "led": 16,
    "button": 0
}

What would be the easiest way to modify the code to remove the GPS and leave it with only UAV mode.

before I attempted to modify the code I wanted to get it to compile, but I'm getting a file missing error 
software\firmware\source\SoftRF\src\platform\ESP8266.h:33:10: fatal error: Exp_SoftwareSerial.h: No such file or directory

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* anonymous user ;

<br>

[![Build Status](https://github.com/lyusupov/SoftRF/actions/workflows/main.yml/badge.svg)](https://github.com/lyusupov/SoftRF/actions/workflows/main.yml "Build Status")

<br>

**Resolution**: invalid
