### ISSUE TITLE
LilyGo T-Echo - Badge - Unintended Power-On Problem

### ISSUE THREAD

**Issue by MollyBe** [lyusupov/SoftRF#160]
When the device is placed inside a bag, there's a risk of accidental button presses leading to the device turning on and unnecessarily draining the battery. It would be beneficial to enhance the button functions to mitigate this issue.

Current layout:
![image](https://github.com/Xinyuan-LilyGO/T-Echo/assets/51837460/2bde690f-aeb0-4747-82e2-f7bb7a194da2)

Recommended layout:
![291071795-2bde690f-aeb0-4747-82e2-f7bb7a194da2(2)](https://github.com/Xinyuan-LilyGO/T-Echo/assets/51837460/cb2a865c-f018-42cb-b83f-49a522d190d5)

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* anonymous user ;
* report has nothing to do with SoftRF firmware - read [**Disclaimer**](https://github.com/lyusupov/SoftRF/wiki/Badge-Edition#disclaimer)

<img width="672" alt="image" src="https://github.com/lyusupov/SoftRF/assets/5849637/3e37ee46-01bf-4e4e-a7a6-cb59bf004a9e">

<br>
<br>

**Resolution**: invalid
