### ISSUE TITLE
SoftRf and Glider Flarm update version 7.22

### ISSUE THREAD

**Issue by maboule6868** [lyusupov/SoftRF#161]
Hello.

Since our gliders have their Flarm updated to V 7.22,  my MkII does not display the gliders anymore. I think because Legacy still use air V 6.
Will legacy be updated to V 7 ??
I fly in France Europe.

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* duplicates https://github.com/lyusupov/SoftRF/issues/157

**Resolution:** duplicate

**Comment by lyusupov** [comment]
[![Release](https://img.shields.io/github/v/release/lyusupov/SoftRF)](https://github.com/lyusupov/SoftRF/releases/tag/1.5.1)
