### ISSUE TITLE
flarm targets are found - but they are always more than 3xx km away.

### ISSUE THREAD

**Issue by btotherunner** [lyusupov/SoftRF#162]
since the update to 1.5 i have the problem that flarm targets are found - but they are always more than 3xx km away.
it seems to me that the gps fix is somehow wrong?
any idea what i can optimize?

i use an lilygo - t-echo fw 1.5

**Comment by lyusupov** [comment]
* report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) ;
* duplicates https://github.com/lyusupov/SoftRF/issues/157

**Resolution:** duplicate

**Comment by lyusupov** [comment]
[![Release](https://img.shields.io/github/v/release/lyusupov/SoftRF)](https://github.com/lyusupov/SoftRF/releases/tag/1.5.1)
