### ISSUE TITLE
V1.5.1 NMEA alarm trigger = None has no effect

### ISSUE THREAD

**Issue by aerilox** [lyusupov/SoftRF#164]
## Hardware
- [ ]   Prime Mark III = Liligo 
![softrf3](https://github.com/lyusupov/SoftRF/assets/50329793/be6de52e-7f61-42f1-979c-f6545a0c58f0)

OLED data incomplete from photo

## Firmware version
![softrf1](https://github.com/lyusupov/SoftRF/assets/50329793/7013fe64-7751-46f1-9949-20baf450f987)

## Firmware settings
![softrf2](https://github.com/lyusupov/SoftRF/assets/50329793/fc96cbf0-0910-49a5-a6f5-e637958da5aa)

## Describe the bug
NMEA alarm trigger = None has no effect. Device sends $PFLAA frame to USB for every device received whatever the distance is. 

## To Reproduce
Settings as above and place a transmitter next to the receiver

## Expected behavior
When NMEA alarm trigger = None -> no $PFLAA frames are sent to USB. Other Legacy frames remain $PFLAU, $PGRMZ

**Comment by lyusupov** [comment]
* [anonymous user](https://berthub.eu/articles/posts/anonymous-help/) ;
* decision when to report or not to report a PFLAA NMEA sentence is up to implementer's discretion

<br>
<br>

<img width="681" alt="image" src="https://github.com/lyusupov/SoftRF/assets/5849637/ef239040-b63a-49eb-b5bf-bed70ae3e2fe">

<br>
<br>

**Resolution**: invalid
