### ISSUE TITLE
NMEA LK8EX1 messages missing on MIDI edition

### ISSUE THREAD

**Issue by diveinstructor** [lyusupov/SoftRF#165]
**ATTENTION** ! 

- Use this form to report bugs in an [**Official Release**](https://github.com/lyusupov/SoftRF/releases) of SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are only allowed when you are ready to implement them by yourself. See [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) list for details ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ ]   Badge
- [ ]   Prime Mark III
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   SkyView Pico
- [ ]   Uni
- [ ]   Ham
- [x]   Midi
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)
![20240604_145024](https://github.com/lyusupov/SoftRF/assets/83521297/1ca9a458-c83f-4189-b1ac-756c3fa3d0c0)

## Firmware version
![Screenshot_20240604_141922_Chrome](https://github.com/lyusupov/SoftRF/assets/83521297/f9b719e6-27b0-4188-a6d6-386ecc8f59bf)

## Firmware settings
![Screenshot_20240604_141630_SoftRF Tool](https://github.com/lyusupov/SoftRF/assets/83521297/fa50f7a9-f2d0-4c1a-8f91-5fdfc82038d2)

## Describe the bug
Despite an installed BME280 baro sensor the NMEA message LK8EX1 is not transmitted

## To Reproduce
Testing with SoftRF app or capturing BLE NMEA messages

## Expected behavior
Transmission of LK8EX1 sentences in the NMEA (BLE) messages.

**Comment by lyusupov** [comment]
* [anonymous user](https://berthub.eu/articles/posts/anonymous-help/) ;
* LK8EX1 message is currently inactive intentionally for all the ESP32-XX devices -

<img width="569" alt="image" src="https://github.com/lyusupov/SoftRF/assets/5849637/ac9f525e-8c78-4771-a734-e8ab7f096dcc">

<br>
<br>

**Resolution**: invalid
