### ISSUE TITLE
Badge Edition, pressure data message fault

### ISSUE THREAD

**Issue by diveinstructor** [lyusupov/SoftRF#166]
**ATTENTION** ! 

- Use this form to report bugs in an [**Official Release**](https://github.com/lyusupov/SoftRF/releases) of SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are only allowed when you are ready to implement them by yourself. See [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) list for details ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [x]   Badge
- [ ]   Prime Mark III
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   SkyView Pico
- [ ]   Uni
- [ ]   Ham
- [ ]   Midi
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

![20240604_150028~2](https://github.com/lyusupov/SoftRF/assets/83521297/bf0803f6-d54e-4afa-8c08-7f9a9b43cb27)

## Firmware version
![Screenshot_20240604_150226_SoftRF Tool](https://github.com/lyusupov/SoftRF/assets/83521297/328053b2-3929-4a54-93ed-be1e305a938c)

## Firmware settings
![Screenshot_20240604_140955_SoftRF Tool](https://github.com/lyusupov/SoftRF/assets/83521297/d24b29b5-515d-4f15-8fc4-d5f5d952c6ad)

## Describe the bug
The NMEA LK8EX1 message contains 999999 as pressure data

## To Reproduce
Check the NMEA message LK8EX1 on SoftRF app or BLE capture

## Expected behavior
LK8EX1 sentence should contain the actual pressure value from the BMx280

**Comment by lyusupov** [comment]
* [anonymous user](https://berthub.eu/articles/posts/anonymous-help/) ;
* to report or not to report a pressure is an implementation decision

<br>
<br>

<img width="471" alt="image" src="https://github.com/lyusupov/SoftRF/assets/5849637/6e40de0b-de87-452c-9b25-5d502aae30a5">

<br>
<br>

**Resolution**: invalid
