### ISSUE TITLE
unable to upgrade a brand new Prime mark III from 1.2+ to 1.5.1

### ISSUE THREAD

**Issue by Olo-Bolo** [lyusupov/SoftRF#167]
**ATTENTION** ! 

- Use this form to report bugs in an [**Official Release**](https://github.com/lyusupov/SoftRF/releases) of SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are only allowed when you are ready to implement them by yourself. See [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) list for details ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ ]   Badge
- [X]   Prime Mark III
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   SkyView Pico
- [ ]   Uni
- [ ]   Ham
- [ ]   Midi
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)

![3](https://github.com/lyusupov/SoftRF/assets/86827815/74f4646a-d23a-41af-8c6e-0fda0bb944db)

## Firmware version
1.2+
<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) status page > (**required**)

## Firmware settings
![2](https://github.com/lyusupov/SoftRF/assets/86827815/3bdd561f-e469-4353-a72b-98041771d185)

<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) settings page > (**required**)
![1](https://github.com/lyusupov/SoftRF/assets/86827815/a7a1d706-55f0-4d0b-b6a2-bb2398900807)

## Describe the bug
It's a brand new prime mk III. I'm unable to upgrade to firmware 1.5.1
upgrade process seems successful, no errors, but the device boots again with v 1.2+

**Comment by lyusupov** [comment]
* [anonymous user](https://berthub.eu/articles/posts/anonymous-help/) ;
* [Release Notes](https://github.com/lyusupov/SoftRF/releases/tag/1.5.1)

<img width="898" alt="image" src="https://github.com/lyusupov/SoftRF/assets/5849637/dbdca6ed-8949-4273-ba00-278b67a362cd">

<br>
<br>

**Resolution**: unable to reproduce
