### ISSUE TITLE
Prime MK III not Sending and Receiving Packets and not accessing GPS Satellites

### ISSUE THREAD

**Issue by LouisTrinczek** [lyusupov/SoftRF#169]
## Hardware

- [ ]   Standalone
- [ ]   Badge
- [x]   Prime Mark III
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   SkyView Pico
- [ ]   Uni
- [ ]   Ham
- [ ]   Midi
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

![WhatsApp Image 2024-06-20 at 21 13 19_bf5c397f](https://github.com/lyusupov/SoftRF/assets/43894665/8e97feb2-fccb-4491-8b30-c2f70c8ded78)
![WhatsApp Image 2024-06-20 at 21 13 37_f2bf2cc8](https://github.com/lyusupov/SoftRF/assets/43894665/b6f7c732-e6d7-40c9-8945-2f530f8165ce)

## Firmware version

![image](https://github.com/lyusupov/SoftRF/assets/43894665/ca0dddff-d73b-46a3-87f5-fd73a5c0ac69)

## Firmware settings
![image](https://github.com/lyusupov/SoftRF/assets/43894665/983807e9-c0dc-4810-a92d-1555d4b74fc9)

## Describe the bug
I have just received the board and updated the firmware to the latest version. I am not able to get the current location, nor to send and receive packets.

## To Reproduce
Plug the board into usb, update firmware, update to latest ogn aircraft database, connect to SoftRF AP, check the settings.

## Expected behavior
The board is sending and/or receiving packets and showing my current location

**Comment by lyusupov** [comment]
> I am not able to get the current location, nor to send and receive packets.
* [**Disclaimer**](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkIII#disclaimer)

<img width="692" alt="image" src="https://github.com/lyusupov/SoftRF/assets/5849637/80325633-60eb-4e5b-86ab-5a54295bbe78">

<br>
<br>

**Resolution**: unable to reproduce
