### ISSUE TITLE
Same address ID in all devices

### ISSUE THREAD

**Issue by CT2IUV** [lyusupov/SoftRF#17]
Hi Linar,

I program 3x esp32 to replace all 8266 but now all the devices get the same ID, in my case softrf-a4ae30, so for the open glider network all 3 devices is the same device because all have the same ID.

I would  like to change the ID, to the Glider ICAO registration Number, or get one ID.

Best regards

**Comment by lyusupov** [comment]
Try out [this commit](https://github.com/lyusupov/SoftRF/commit/044ca314ef73a5b9ebc505118ec6298cecef734a)

Report if it works for you.

**Comment by CT2IUV** [comment]
Hi Linar,

Yes it works.

I have a problem with the use off the bluetooth but is my issue, is
someting missing in my library i think. i will check.

But the important for you now is, all my 3 devices now have diferent ID.

I edit all the important code for garanty all devices have diferent ID
using the mac address and it works.

Thanks

Regards

Nuno Freitas

2018-04-22 13:45 GMT+01:00 Linar Yusupov <notifications@github.com>:
