### ISSUE TITLE
Vertical Speed in SkyView EZ instead of Battery Power

### ISSUE THREAD

**Issue by antonka2000** [lyusupov/SoftRF#170]
## Hardware
- [X]   Prime Mark III
- [X]   SkyView EZ

## Firmware version

1.5.1
0.13
## Describe the bug

Great Soft and Hardware!!
It would be helpful in daily use to have the Vertical Speed of the other A/C beside the A/C - Symbol or instead of the Battery Power.
So I see if the others are climbing or not...

One more "feature Request" - The Obstacle Database would be helpful as well.
Granted, I have to buy ist. But as far as I see, I cannot make obstacle Visible in SoftRF or SkyView

**Comment by lyusupov** [comment]
* [**anonymous user**](https://berthub.eu/articles/posts/anonymous-help/) ;
* [**template**](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) **sections** are incomplete ;

<img width="887" alt="image" src="https://github.com/lyusupov/SoftRF/assets/5849637/2bd7bd53-2ce0-4615-a316-3e2f98041a7f">

* [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md)

**Resolution**: invalid
