### ISSUE TITLE
Save and Restart has no effect

### ISSUE THREAD

**Issue by cloudsun9** [lyusupov/SoftRF#172]
**ATTENTION** ! 

- Use this form to report bugs in an [**Official Release**](https://github.com/lyusupov/SoftRF/releases) of SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are only allowed when you are ready to implement them by yourself. See [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) list for details ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [x]   Badge
- [ ]   Prime Mark III
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   SkyView Pico
- [ ]   Uni
- [ ]   Ham
- [ ]   Midi
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)
![20240928_232846](https://github.com/user-attachments/assets/9b662773-2f56-4bcd-9c9b-99c125ab8f6f)

## Firmware version
s140 6.1.1

<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) status page > (**required**)
![Screenshot_20240928_233825438_SoftRF Tool](https://github.com/user-attachments/assets/39d3d2a4-64e8-4860-8732-f18eb368f0a5)
## Firmware settings

<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) settings page > (**required**)
![Screenshot_20240928_235107209_SoftRF Tool](https://github.com/user-attachments/assets/c3540a4a-a884-4c6e-a47d-5c31349232e6)

## Describe the bug
In settings I select FANET and Paraglider, press upload button (top right), press Save and Restart. 
SoftRF Tool disconects but nothing happens, everything is still default even if I manually restart the device.

## To Reproduce
I expect this is a rare instance, permissions maybe?

## Expected behavior
Changes to be saved to the device

**Comment by lyusupov** [comment]
**SoftRF Tool** works fine to me.

* [anonymous user](https://berthub.eu/articles/posts/anonymous-help/) ;
* the [**SoftRF Tool**](https://play.google.com/store/apps/details?id=com.dda.softrftool) is a third-party app which has nothing to do with this SoftRF GitHub repo. Ask for support (if any) on the [app's home page](https://play.google.com/store/apps/details?id=com.dda.softrftool) in Google Play ;
* read the [**Disclaimer**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool#disclaimer) 
![image](https://user-images.githubusercontent.com/5849637/188066210-d664eb39-2fd7-415c-8bf6-0eba68796453.png)

Highly likely that it is your local smartphone/Android/Version/Bluetooth issue.

Try either:
1) SoftRF Tool over **USB**, or
2) [SoftRF online 'general purpose' settings tool](http://soaringweather.no-ip.info/SoftRF/basic.html) on a laptop with Chrome and Bluetooth

<br>
<br>

**Resolution**: unable to reproduce
