### ISSUE TITLE
Badge: Does not start after power-off when on battery

### ISSUE THREAD

**Issue by peclik** [lyusupov/SoftRF#173]
## Hardware

- [x]   Badge

## Firmware version

https://github.com/lyusupov/SoftRF/commit/6f74a336d84b16a5f6992f439b662820a4f10a44

## Describe the bug

When the device is on battery only (no USB connection), after turning the device off with the button 2, it is possible to turn the device on with any of buttons.

## To Reproduce

1. Disconnect USB
2. Turn the device off with button 2
3. Try to turn device on (no success)

## Patch

* In ```nRF52.h``` uncomment ```#define EXCLUDE_PMU```  (https://github.com/lyusupov/SoftRF/blob/6f74a336d84b16a5f6992f439b662820a4f10a44/software/firmware/source/SoftRF/src/platform/nRF52.h#L271).
* In ```nRF52.cpp``` move power pins configuration block up in  [nRF52_setup()](https://github.com/lyusupov/SoftRF/blob/6f74a336d84b16a5f6992f439b662820a4f10a44/software/firmware/source/SoftRF/src/platform/nRF52.cpp) - see 
[patch](https://github.com/user-attachments/files/17356993/nRF52_setup.patch).

**Comment by lyusupov** [comment]
<img width="876" alt="image" src="https://github.com/user-attachments/assets/05a54b3f-cba1-4100-9563-859be79c202c">

Both most recent [**Release 1.5.1**](https://github.com/lyusupov/SoftRF/releases/tag/1.5.1) and current 'master' branch wakes  **Badge** device up fine to me when powered by battery.

<br>
<br>

**Resolution**: unable to reproduce
