### ISSUE TITLE
T-Echo (badge, v1.5.1) doesn't turn off

### ISSUE THREAD

**Issue by jorisrobijn** [lyusupov/SoftRF#174]
## Hardware

- [ ]   Standalone
- [x]   Badge
- [ ]   Prime Mark III
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   SkyView Pico
- [ ]   Uni
- [ ]   Ham
- [ ]   Midi
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder

![2024-10-26 10 33 27](https://github.com/user-attachments/assets/929307a9-39a7-4d76-a53b-0361a8222af2)

## Firmware version

![2024-10-26 10 35 25](https://github.com/user-attachments/assets/c3a2d010-1f6e-416b-aec0-a753ec00d2f0)

## Firmware settings

![2024-10-26 10 38 41](https://github.com/user-attachments/assets/c7aa5277-890c-4899-8e7b-237bb97ccf55)
![2024-10-26 10 38 47](https://github.com/user-attachments/assets/b8f0c2e5-f446-4046-8bde-433a06fc3e0a)

## Describe the bug
When pressing the lower button for a long time, softrf attempts to shut down with it's "POWER OFF   SCREEN SAVER"  message. However immediately after that, it restarts.
Also when the battery is empty, the power off results in restarting, draining the battery to 2.6 V before it finally stops. I guess some hardware protection then refuses to power the device.
It is worth noting that the meshtastic software that was on this device before did manage to shut it down.

## To Reproduce

Install mentioned firmware, try to power off by pressing button long.

## Expected behavior

Power off when pressing button long

**Comment by lyusupov** [comment]
The **MODE** button works fine to me with 1.5.1 firmware.

> softrf attempts to shut down with it's "POWER OFF SCREEN SAVER" message

One is likely activating the touch sensor to get this message:
https://github.com/lyusupov/SoftRF/wiki/Badge-Edition.-Display-care#long-term-storage

This is not a regular power off procedure...

> It is worth noting that the meshtastic software that was on this device before did manage to shut it down.

**It is responsibility of a user to revert a T-Echo device into SoftRF & LilyGO factory conditions** after use of an alternative firmware.

[**Release 1.5.1 Notes**](https://github.com/lyusupov/SoftRF/releases/tag/1.5.1)<br>
<img width="761" alt="image" src="https://github.com/user-attachments/assets/15caad4f-365a-45e3-ab1e-20c63c885663">


One could try to apply:
1) [**Meshtastic factory erase procedure**](https://meshtastic.org/docs/getting-started/flashing-firmware/nrf52/nrf52-erase/), and/or
2) [**revert nRF52840 bootloader into factory default state**](https://github.com/Xinyuan-LilyGO/T-Echo/tree/main/bootloader)

<br>

**Resolution**: unable to reproduce
