### ISSUE TITLE
Unable to install SoftRF on Card Edition

### ISSUE THREAD

**Issue by ubx** [lyusupov/SoftRF#176]
**ATTENTION** ! 

- Use this form to report bugs in an [**Official Release**](https://github.com/lyusupov/SoftRF/releases) of SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are only allowed when you are ready to implement them by yourself. See [CONTRIBUTING](https://github.com/lyusupov/SoftRF/blob/master/CONTRIBUTING.md) list for details ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ ]   Badge
- [ ]   Prime Mark III
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   SkyView Pico
- [ ]   Uni
- [ ]   Ham
- [ ]   Midi
- [ ]   Mini

- [ ]   Academy
- [ ]   Lego
- [ ]   ES Edition
- [ ]   Balkan
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   WebTop Serial
- [ ]   WebTop USB
- [ ]   UAT978 module
- [ ]   Flight Recorder
- [X]  Card Edition

![20241110_100058](https://github.com/user-attachments/assets/9f69449b-4c1f-4848-a2dd-db9e2a4c94a5)
![20241110_100108](https://github.com/user-attachments/assets/1ae1cbf7-d1c2-4f0d-9e06-1373ac3929cd)

## Firmware version
![Screenshot From 2024-11-10 10-05-39](https://github.com/user-attachments/assets/05bd8af1-bd77-420c-b659-9cd80808929d)

## Firmware settings
N/A

## Describe the bug
Following the [Card Edition Quick Start Installation](https://github.com/lyusupov/SoftRF/wiki/Card-Edition.-Quick-start#installation), after copying the SoftRF firmware binary into the Card Edition (T1000-E volume) and turning on the power of the SoftRF unit by pressing and releasing the button, the expected 4 tones do not play, and the green LED remains dark.

Restoring the T1000-E device with the Meshtastic firmware firmware-tracker-t1000-e-2.5.11.8e2a3e5.uf2 shows that the device is functioning correctly, i.e., Meshtastic runs as expected.

## To Reproduce
Follow the [Card Edition. Quick start Installation](https://github.com/lyusupov/SoftRF/wiki/Card-Edition.-Quick-start#installation). 

## Expected behavior
The T1000-E device should be accessible via the SoftRF Tool and/or XCSoar.

**Comment by lyusupov** [comment]
None of upcoming
* [**Eco**](https://github.com/lyusupov/SoftRF/wiki/Eco-Edition)
* [**Card**](https://github.com/lyusupov/SoftRF/wiki/Card-Edition)
* [**Cozy**](https://github.com/lyusupov/SoftRF/wiki/Cozy-Edition)

**Editions** are listed in the current version of [**Issue Template**](https://github.com/lyusupov/SoftRF/blob/1d9aff0b6bc99fa482a936258e7ff919ff7d378d/.github/ISSUE_TEMPLATE/softrf-issue-template.md)

<img width="381" alt="image" src="https://github.com/user-attachments/assets/84499e6f-278a-4523-896e-4b436cb529bf">

<br>
<br>

This means that reporting of an issue on any of these Editions is not applicable yet.

<br>

**Resolution**: invalid
