### ISSUE TITLE
GDL90 option not available in SoftRF Tool

### ISSUE THREAD

**Issue by d3mac123** [lyusupov/SoftRF#177]
## Firmware version: s140 6.1.1 - Software revision: 1.6
![IMG_5921 Large](https://github.com/user-attachments/assets/6e5d3766-d8b3-4296-8951-28b387291ce9)

![IMG_5922 Large](https://github.com/user-attachments/assets/08f86f10-db9b-4784-838f-ecfee1fbd21b)

## Firmware settings

<  screenshot of WebUI and/or [**SoftRF Tool**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool) settings page > (**required**)

## Describe the bug
Hi, I am in the USA (915Mhz). I just got a new phone (purchased only to configure the T-Echo), and installed the APK (SoftRF Tool is not available in the Google Play store). I cannot find a way to get ADSB traffic (GDL90) on my Badge. Is it possible? If so, which protocol should I use: Legacy? OGNTP? OGNTP doesn't seem very used around me

**Comment by d3mac123** [comment]
After posting it, I installed firmware 1.6 but got the same results: no GDL90 option.

**Comment by lyusupov** [comment]
* ADS-B is not listed in the **Badge Edition** [protocols specs](https://github.com/lyusupov/SoftRF/wiki/Badge-Edition#compatibility-3) ;
* the [**SoftRF Tool**](https://play.google.com/store/apps/details?id=com.dda.softrftool) is a third-party app which has nothing to do with this SoftRF GitHub repo. Ask for support (if any) on the [app's home page](https://play.google.com/store/apps/details?id=com.dda.softrftool) in Google Play ;
* read the [**Disclaimer**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-Configuration-Tool#disclaimer) 
![image](https://user-images.githubusercontent.com/5849637/188066210-d664eb39-2fd7-415c-8bf6-0eba68796453.png)

**Resolution:** invalid
