### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by LilyGO** [lyusupov/SoftRF#21]
I installed all the libraries, but the compilation failed, of course, I also installed the configuration file.
*********************************************
Build options changed, rebuilding all
Archiving built core (caching) in: C:\Users\15840\AppData\Local\Temp\arduino_cache_468712\core\core_espressif_esp32_esp32_PSRAM_disabled,PartitionScheme_default,FlashMode_dio,FlashFreq_80,FlashSize_4M,UploadSpeed_921600,DebugLevel_none_4cfcc43f8cdc37390bbcfde39fb1d404.a
libraries\Wire\Wire.cpp.o:(.bss.Wire1+0x0): multiple definition of `Wire1'

sketch\Platform_ESP32.cpp.o:(.bss.Wire1+0x0): first defined here

C:\Users\15840\AppData\Local\Temp\arduino_build_811450/arduino.ar(HardwareSerial.cpp.o):(.bss.Serial1+0x0): multiple definition of `Serial1'

sketch\Platform_ESP32.cpp.o:(.bss.Serial1+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board ESP32 Dev Module.
***********************************************
Then I burned the bin file on T-Beam, but the serial port information is garbled.
![534_1](https://user-images.githubusercontent.com/31160602/42410599-90645940-821e-11e8-838e-664f492fb651.png)

**Comment by lyusupov** [comment]
You are using wrong destination addresses.<br>
SoftRF.ino.bin should go into 0x10000<br>
SoftRF.ino.partitions.bin should go into 0x8000<br>

For reference, read **firmware.txt** file that comes inside the firmware's zipfile.

**Comment by lyusupov** [comment]
And I am curious, why are you using 26 MHz crystal setting?

**Comment by LilyGO** [comment]
Thank you!
