### ISSUE TITLE
Battery holder connection

### ISSUE THREAD

**Issue by ZaxCZ** [lyusupov/SoftRF#22]
The battery holder wires should be connected to the input of the DC - DC converter, right? I just want be sure, because it isn't clear to me from the photos or the schematics.

**Comment by lyusupov** [comment]
Good question!

Revision 1.1 of the Shield does not have specific soldering points (holes) for the 2xAA battery holder wires.


Normally, the holder should be soldered directly to **Charging port** (DC jack) like shown on this photo:<br>


![battery-connection](https://user-images.githubusercontent.com/5849637/42417195-311250be-828c-11e8-9027-0d82319f4f92.jpg)
