### ISSUE TITLE
Qpython Can not run

### ISSUE THREAD

**Issue by LilyGO** [lyusupov/SoftRF#23]
### I installed Qpython on Google _play, but the interface is inconsistent. Maybe it's a new version.
![screenshot_20180709-184827](https://user-images.githubusercontent.com/31160602/42445915-26239750-83a7-11e8-9fb5-c90dca76b332.png)
### Then I transferred the file to my phone and ran it, but there was no main.py.
![screenshot_20180709-184118](https://user-images.githubusercontent.com/31160602/42445980-592ced54-83a7-11e8-9081-5132a277f543.png)
### This python library, I downloaded it. But I don't know if the installation was successful.

**Comment by LilyGO** [comment]
![screenshot_20180709-185156](https://user-images.githubusercontent.com/31160602/42446298-52d6bfb0-83a8-11e8-985e-8b5e24c31a0c.png)

**Comment by lyusupov** [comment]
This is not a QPython support site.
Known good version of  QPython that works with the Emulator is 1.2.5

**Emulator** is a deprecated software. It only has sense for GNSS-less **Prime Edition** in Bridge mode.
**Prime Edition** is a part of Archive now.

All current GNSS or UAV-capable SoftRF Editions do operate in Normal mode and thus they do not need Emulator anymore.

**Comment by LilyGO** [comment]
What you mean is that the SoftRF-firmware-v1.0-rc4-ESP32 firmware does not require an Emulator. Can continue to work normally, right?

**Comment by lyusupov** [comment]
Most people who deal with SoftRF project are pilots.
They are typically already familiar with either FLARM, OGN Tracker or PilotAware.
So they mutually understand basic principles of the technology.

From very beginning (v 0.9) SoftRF firmware has WebUI mode selector in 'Settings' area.
If target device (particular SoftRF Edition) has built-in GNSS source - this mode selector is to be set in "Normal" position.
If target device does NOT have GNSS - the only option applicable is "Bridge" mode, when all data processing is off-loaded from the SoftRF device onto an external Androd or Raspberry Pi host.

**Comment by lyusupov** [comment]
[Quick start](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkII.-Quick-start) section is added into the Wiki. Hope that this will help you and other beginners.
