### ISSUE TITLE
Baro Calibration - Question

### ISSUE THREAD

**Issue by PeteMilligan99** [lyusupov/SoftRF#26]
New_SeaLevelPressure=pow((((ThisAircraft.altitude*0.0065)/(bmp280.readTemperature() + 273.15F))+1), (1.0/0.190223F))*bmp280.readPressure();
Sea_Level_Pressure=New_SeaLevelPressure/100;
ThisAircraft.pressure_altitude = baro_chip->altitude(Sea_Level_Pressure);

To predictably set the pressure, a few conditions need to be true. HDOP should be low. Num Satellites to be high. Shouldn't be moving & should not be in the air.

Hi Linar, Can you confirm my thinking on the conditions & what the appropriate If{ statement might be?
(Great project BTW).

Cheers,

Pete

**Comment by lyusupov** [comment]
Pete,

barometic sensors support code was added into SoftRF in accordance with these guidelines:
1)  selected chip model has to be modern and smart enough to keep most of "physics" inside it's hardware. If one particular chip needs a lot of compensation stuff from software - just get rid of it and proceed to the next one ;
2) most of software required to bring up the baro chip has to be open source, well maintained and located on GitHub. SoftRF works with the chip on a high level. Libraries take care of the chip internals. If something wrong happens with the code - we should file a GitHub ticket to developer of this library ;
3) SoftRF baro support code itself does not need to know actual barometric altitude of the aircraft. It is not in use for collision avoidance. Instead, SoftRF is just forwarding raw standard pressure altitude value though NMEA to an upper layer software, such as XCSoar to apply further calibration, compensation and other "mathematics".
