### ISSUE TITLE
Integration with iNav

### ISSUE THREAD

**Issue by Tdogb** [lyusupov/SoftRF#33]
Hi,
I made a big post about integration of SoftRF over on the iNav project so you can read that [here](https://github.com/iNavFlight/inav/issues/3849). INav is flight control firmware for UAVs/multirotors/fixed wings. They have implemented an on screen display that shows flight data. What I describe in the post is a proposal to add another GPS input to the OSD in order to see friends (other UAVs) and full size aircraft while flying. This would make flying formation with fixed wings more fun and safer. What do you guys think of this idea?
Thanks,
Tanner Beard

**Comment by lyusupov** [comment]
New feature requests do not subject for taking into consideration unless they are coming from co-developers.
