### ISSUE TITLE
RC5 on TTGO T_Beam

### ISSUE THREAD

**Issue by nbonniere** [lyusupov/SoftRF#36]
I have t22_v07 board (no Baro, no OLED) with RC4 that I tried to upgrade to RC5. I first tried with Web Gui and at first I saw RC5 shown, but on reboot, I get a short blue LED flash and then it goes off.  Board no longer boots.  I tried manual flash with ESP32 tool, but same issue. I then tried to flash RC4 back in and was successful. So I tried RC5 again, but same issue. I tried RC4 again and it worked OK, back to full function on 915 MHz.
Conclusion RC4 works OK and can be flashed into this board, but published zip file for RC5 does NOT work on this board.

**Comment by lyusupov** [comment]
Issue was filed not in compliance with [this template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) (offered automatically for each new issue).

Re-file the issue in accordance with the template, please,

**Resolution**: invalid.
