### ISSUE TITLE
T-Beam Program Download Erratic

### ISSUE THREAD

**Issue by chillmf** [lyusupov/SoftRF#37]
I have several t-beam boards and have successfully downloaded applications such as SoftRf and ESP-sc-gway.

These applications run well and I am pleased with the operation.

However, I have continued to have problems downloaded compiled code using both the Arduino IDE and ESP Download Tool V3.6.4.

Usually I get the error message "A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header"

Has anyone else had a similar problem.

If so have you found a solution.

Thanks for the help.

Charley

**Comment by lyusupov** [comment]
Issue is not related to SoftRF project.
And It is duplicate for: https://github.com/LilyGO/TTGO-T-Beam/issues/12

**Resolution**: invalid
