### ISSUE TITLE
SoftRF PCB

### ISSUE THREAD

**Issue by SwiftFlying** [lyusupov/SoftRF#42]
Hi,
  Are you interested in designing a PCB for SoftRF?
 Tom

**Comment by lyusupov** [comment]
I do not object to independent open hardware designers to develop non-commercial equipment, compatible with SoftRF firmware.
That open hardware **SMD** PCB design will make sense only if it is published
as a ready-to-use, complete PCB&A package. Non-experienced builder should be able
to place an order for the SMD PCB&A service by doing few mouse clicks and expect to receive
a set of fully soldered & assembled boards.
