### ISSUE TITLE
Error in Relative GPS position 

### ISSUE THREAD

**Issue by DineshkumarGA** [lyusupov/SoftRF#45]
Invalid.
Will reword

**Comment by lyusupov** [comment]
Read yourself your comment and tell me what should I guess based on information you've provided. 
**Re-file the ticket in accordance with reference template**. 

**In addition to that listed int the template**, please, add (for each of the SoftRF units involved):
1) screenshots of the moving map (with coordinates of each traffic instance)  ;
2) screenshots of NMEA "monitor" window in XCSoar (and GDL90 in FF, if possible) ;
3) capture of NMEA output over USB (serial port, 38400 baud rate)
