### ISSUE TITLE
SoftRF WiFi connection problem on Kobo Touch 2

### ISSUE THREAD

**Issue by dadyeah** [lyusupov/SoftRF#46]
Hi, this is probably a Kobo issue but I've had no luck finding a solution. SoftRF connects fine to an Android phone but will not connect to my Kobo Touch 2 (which connects ok to other WiFi sources)  . Any help much appreciated

**Comment by lyusupov** [comment]
Issue was filed not in compliance with [this template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) (offered automatically for each new issue).

**Resolution**: invalid.

<br>
<br>

![softrf-kobo-mini](https://user-images.githubusercontent.com/5849637/51783666-53e20d80-214e-11e9-9fd3-592c4efa5869.jpg)

**Comment by dadyeah** [comment]
Fixed now with the help of DK in Texas on Gitter. Many thanks
