### ISSUE TITLE
Security: Other pilots could disable your transmit while you're flying

### ISSUE THREAD

**Issue by bruceme** [lyusupov/SoftRF#49]
Since the wifi password is well known, any other pilots on the field could login and change any setting.  Let's lock setup while flying?

**Comment by lyusupov** [comment]
I don't qualify motion based WebUI denial of access as a good idea. It will prevent the PIC himself from changing SoftRF settings while in flight. 

Current "security method" is Wi-Fi transmit power limitation. It is not perfect, but it works Ok within radius of 10-15 meters area.

In addition to that, on UAV Edition (it is **un-manned**), it senses "ARMED" state of the AP and disables Wi-Fi transmit power at all when the UAV is ready to fly. This prevents from interference with 2.4 GHz RC and telemetry RF waves flow. 

I was and is still considering to give an option for a user to change the Wi-Fi password.
Associated action should be accompanied  "password reset option" (**for all of the SoftRF Editions**, which is not very trivial task) when the user will forget the password.
So, I keep it in mind, but postponed this activity until better times.
