### ISSUE TITLE
usage along side pingrx

### ISSUE THREAD

**Issue by geofrancis** [lyusupov/SoftRF#5]
can the UAV version be used alongside a pingrx?

**Comment by lyusupov** [comment]
SoftRF UAV Edition is occupying one telemetry slot of an AP.
As long as:
- operating RF bands are different ;
- AP provides enough current ;
- AP is compatible with MAVLINK 1.0 ;
- AP's firmware is able to manage different sources of ADS-B data ;
I see no issues to use the SoftRF alongside with any other devices of similar purpose.
