### ISSUE TITLE
FEATURE-Request: Type 4 (Groundstation) FANET frames

### ISSUE THREAD

**Issue by commander-chris** [lyusupov/SoftRF#53]
Hi,

Thank you for the terrific work!

Is it possible to implement Type 4 FANET frames ("Service", see excerpts below, from [FANET Protocol](https://github.com/3s1d/fanet-stm32/blob/master/Src/fanet/radio/protocol.txt)) into SoftRF to run a FANET groundstation (on the paragliding landing site) on a TTGO T-Beam? Would be awesome to TX current measured weather/wind conditions to the pilots in the air...

Thinking of connecting a BMP280 (or preferably a GY-91 to be able to calibrate the wind direction using a tilt compensated compass reading) and a TX-20 to the TTGO via the TTGO's I2C buses, reading the data from the sensors, and transmitting them to the pilots via FANET type 4 frames.

> ------------
> 
> Service (Type = 4)
> 
> [Byte 0]	Header	(additional payload will be added in order 6 to 1, followed by Extended Header 7 to 0)
> bit 7		Internet Gateway (no additional payload required, other than a position)
> bit 6		Temperature (+1byte in 0.5 degree, 2-Complement)
> bit 5		Wind (+3byte: 1byte Heading in 360/256 degree, 1byte speed and 1byte gusts in 0.2km/h (each: bit 7 scale 5x or 1x, bit 0-6))
> bit 4		Humidity (+1byte: in 0.4% (%rh*10/4))
> bit 3		Barometric pressure (+2byte: in 10Pa, offset by 430hPa, unsigned little endian (hPa-430)*10)
> bit 2		TBD
> bit 1		State of Charge  (+1byte lower 4 bits: 0x00 = 0%, 0x01 = 6.25%, .. 0x0F = 100%)
> bit 0		Extended Header (+1byte directly after byte 0) (TBD, it may indicate the number of available landmarks) 
> 		The following is only mandatory if no additional data will be added. Broadcasting only the gateway flag doesn't require pos information. 
> [Byte 1-3 or Byte 2-4]	Position	(Little Endian, 2-Complement)		
> bit 0-23	Latitude	(Absolute, see below)
> [Byte 4-6 or Byte 5-7]	Position	(Little Endian, 2-Complement)
> bit 0-23	Longitude   (Absolute, see below)
> + additional data according to the sub header order (bit 6 down to 1)
> 
> ------------

Thanks, best regards,
Chris

**Comment by lyusupov** [comment]
Ticket is filed not in compliance with [the template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md).

**Resolution**: invalid.
