### ISSUE TITLE
Flarm and SoftRF not seeig each other 

### ISSUE THREAD

**Issue by sixpack-de** [lyusupov/SoftRF#61]
- [X ]   Prime Mark II
- [ ]   Standalone
- [ ]   UAV
- [ ]   UAT module
- [ ]   SkyView

![HW small](https://user-images.githubusercontent.com/51480811/59678122-d9349000-91cb-11e9-9610-1a00db7f261c.JPG)

## Firmware version
![IMG_0074](https://user-images.githubusercontent.com/51480811/59678162-eea9ba00-91cb-11e9-9784-152fbd2a517c.JPG)

## Firmware settings

![IMG_0075](https://user-images.githubusercontent.com/51480811/59678353-7abbe180-91cc-11e9-8032-272c52ca35e1.JPG)

## Describe the bug (or ask a question)
Probably its a setting I am to dumb to set. 

System is stating to send out Flarm but cannot be recieved by Flarm systems (tested at my glider port and recreated with a dedicated Flarm Setup, see above). 

System is not recieving (stays at 0) also tested at airport and recreated at home 

Please be not confused with the skyview I was testing something when the pic was done, the ipad screen is the Mark II live.

## Expected behavior
I was expecting to see FLARM equipped gliders (and be seen).

Cool project BTW!!!

**Comment by Ben64Smith** [comment]
Change protocol from OGNTP to LEGACY then it will se and be seen by FLARM.

**Comment by sixpack-de** [comment]
I will test tonight ... THX!!

**Comment by lyusupov** [comment]
https://github.com/lyusupov/SoftRF/wiki/Settings#protocol-1

**Resolution:** invalid
