### ISSUE TITLE
ringLED in Prime Edition MkII

### ISSUE THREAD

**Issue by Gapeev1** [lyusupov/SoftRF#62]
Hello, is it possible to connect address LEDs, such as in Standalone, to the TTGO T-Beam Prime Edition MkII board?

**Comment by lyusupov** [comment]
**There is no support for anything except bare T-Beam board**.<br>

For '_aftermarket ideas_' - talk with community folks on [this Gitter channel](https://gitter.im/lyusupov/SoftRF).

**Comment by Gapeev1** [comment]
I collected Prime Mark II and wanted to connect the LED ring to the TTGO T-Beam in addition to the SkyView EZ screen. But on TTGO T-Beam there is no port D1 to which they were connected in Standalone Edition
