### ISSUE TITLE
Removal of proprietary data

### ISSUE THREAD

**Issue by eroom1966** [lyusupov/SoftRF#63]
Please remove the PilotAware Proprietary data under the following repository locations

https://github.com/lyusupov/SoftRF/blob/master/software/data/Aircrafts/paw.db
https://github.com/lyusupov/SoftRF/blob/master/software/data/Audio/paw_voices.zip

These are available under software license, and no permission has been granted for their use outside of the scope of the PilotAware product

**Comment by lyusupov** [comment]
Issue was filed not in compliance with [this template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) (offered automatically for each new issue).

**Resolution**: invalid.
