### ISSUE TITLE
Prime Mark II Vario information on glidertracker.de

### ISSUE THREAD

**Issue by FuzoCZ** [lyusupov/SoftRF#66]
Hello. I want to ask. Prime Mark II does not show all the information. It does not show the rate of ascent or descent on glidertracker.de and other websites. I have installed BMP280 module and it is not for one but for more devices. Other OGN devices show the rate of climb. 
![Screenshot_20190710-131824](https://user-images.githubusercontent.com/55080483/64512612-19953d00-d2e7-11e9-9d80-160ae6a6fd3a.png)
![Screenshot_20190710-132847](https://user-images.githubusercontent.com/55080483/64512625-1f8b1e00-d2e7-11e9-8412-73f4218f8358.png)
![Screenshot_20190710-140348](https://user-images.githubusercontent.com/55080483/64512634-244fd200-d2e7-11e9-93cb-0b8315b9c75d.png)
![Screenshot_20190907-152215](https://user-images.githubusercontent.com/55080483/64512683-36ca0b80-d2e7-11e9-9b6d-e8add907e0f0.png)

![Screenshot_20190730-190016](https://user-images.githubusercontent.com/55080483/64513035-f9b24900-d2e7-11e9-8ba8-a20ab345e86c.png)

Is this the normal behavior of this device?

Thank you very much. I admire your work. One day I want to be good, like half of you.

**Comment by lyusupov** [comment]
Issue was filed not in compliance with [this template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) (offered automatically for each new issue).

**Resolution**: invalid
