### ISSUE TITLE
SoftRF on Lora32 Oled

### ISSUE THREAD

**Issue by mbatini** [lyusupov/SoftRF#71]
**ATTENTION** ! 

- Use this form to report bugs in released SoftRF firmware, hardware and web pages only ;
Not a bug

- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
Looked into but couldn't find out info

- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are allowed only when you are ready to implement them by yourself ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Prime Mark II
- [ ]   Standalone
- [ ]   UAV
- [ ]   Raspberry Edition
- [ ]   UAT module
- [ ]   SkyView
- [ ]   Flight Recorder

Wemos Lora32 Oled

< photo of your hardware > (**required**)

## Firmware version

<  screenshot of WebUI status page > (**required**)

## Firmware settings

<  screenshot of WebUI settings page > (**required**)

## Describe the bug (or ask a question)
SoftRF repo cloned and compiled and flashed
Is it possible to use a neo 6m gps module ? Looking inside code for pin definition, but need hints. 

I see that connecting GPS RX to board PIN 16 (OLED RST) Oled shows up. But would like any hint.

TIA
![IMG_20191023_223513](https://user-images.githubusercontent.com/34915878/67433467-7a9f7880-f5e8-11e9-9bee-5aa14f46ee1b.jpg)
![IMG_20191023_225555](https://user-images.githubusercontent.com/34915878/67433468-7a9f7880-f5e8-11e9-9d48-fa64b39a0d87.jpg)

**Comment by lyusupov** [comment]
This board [does not perform good enough](https://github.com/lyusupov/SoftRF/releases/tag/1.0-rc2) to qualify it for SoftRF purpose.

**Relosution**: invalid

**Comment by nbonniere** [comment]
Seems like a reasonable board, with SD card interface (could record an IGC file), and needs an external GPS (simple enough to connect), but has no PSRAM. Is the lack of PSRAM why it is not good ?

**Comment by nbonniere** [comment]
I guess there are two versions. V2.1 seems OK.
