### ISSUE TITLE
Protocol for Flarm and OGN

### ISSUE THREAD

**Issue by SuckoSU** [lyusupov/SoftRF#72]
Hello,
is it possible to see on Prime Mark II FLARM and OGN tracker together?
Or I can only set OGNTP protocol for OGN tracker OR Legacy protocol for FLARM?
Thank you for help

**Comment by lyusupov** [comment]
[No](https://gitter.im/lyusupov/SoftRF?at=5c589efaceb5a2264f940238).
For use of 2 protocols at the same time you need 2 SoftRF units.
