### ISSUE TITLE
Some documentation issues installing the SoftRF Raspberry PI edition

### ISSUE THREAD

**Issue by acasadoalonso** [lyusupov/SoftRF#75]
**ATTENTION** ! 

- Use this form to report bugs in released SoftRF firmware, hardware and web pages only ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are allowed only when you are ready to implement them by yourself ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [x ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

Doc issues

## Firmware version

Doc issues
## Firmware settings

Doc issues

## Describe the bug (or ask a question)

Some minor documentation issues that I found during the installation of the SoftRF Raspberry Pi edition.
I need to start to say that the documentation is very good, very clear and the support by Linar is outstanding. Thanks Linar

The first problem that I found is that I discovered that I need to install the firmware/software of Dragino, may me obvious, but better if it is explicitly documented.

I found the doc here:  http://wiki.dragino.com/index.php?title=Lora/GPS_HAT
and the details for Raspberry Pi 3 here: http://wiki.dragino.com/index.php?title=Getting_GPS_to_work_on_Raspberry_Pi_3_Model_B

be aware that it mentions that it needs to install a a new device tree overlay, called: 
pi3-miniuart-bt-overlay.dtb  
however that is include on the latest version of Raspbian distro buster.
It mentions that we need to include on the /boot/config.txt the device 
dtoverlay=pi3-disable-bt-overlay
but the real name is: 
dtoverlay=pi3-disable-bt
be careful with the copy and paste.

When I tried to build the SoftRF and copy the SoftRF and libraries directories, I run the command:
make -f Makefile.RPi
I discovered that the libraries was built with the automake 1.15.1, however the last version of Rasbian buster is using automake 1.16, so I need to run the command : autoreconf -f -i in order to update to the version 1.16

I initially installed an old version of the dump1090, now Linar mention of the documentation that the supported version is the one from mutability (unmantained). I will try to submit a PR in order to support the dump1090 from FlightAware that seems to be the latest one.

For me the command http://localhost:8080/data/aircraft.json does not work.
I used the following command to start dump190

 ~/src/dump1090/dump1090 --interactive --net --no-fix --net-ro-size 500 --net-ro-rate 5 --net-heartbeat 60 --gain -10 --write-json /tmp

and I have the following script to call SoftRF:

#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT SIGINT SIGTERM
function ctrl_c() {
        echo "** Trapped CTRL-C"
        echo quit | nc -N localhost 30007
        exit
}

stty -F /dev/ttyAMA0 9600 raw; { echo "{class:SOFTRF,mode:RELAY,nmea:{private:true}}" ; cat /dev/ttyAMA0 ; } | sudo ~/src/SoftRF/SoftRF/SoftRF &
while  [ 1 ]
do
        cat /tmp/aircraft.json | nc -N localhost 30007
        sudo rm /tmp/hist* &> /dev/null
        sleep 12
done
echo quit | nc -N localhost 30007

so every 12 seconds I send the aircraft.json file to SoftRF thru port 30007 

Thanks again Linar for the great job and the great support.
AC/.

**Comment by lyusupov** [comment]
This is not an issue report.

If you want to improve documentation:
- fork the SoftRF repo
- copy my .md file or create your own one
- add your 'improvements'
- give me for review

If  I'll decide that your 'improvements' deserve acceptance into SoftRF 'master' - I may consider to accept you PR.

This is how it works in Open Source & GitHub 'world'.

**Resolution**: invalid
