### ISSUE TITLE
Retro STM32F1 compile error - region `FLASH' overflowed by 268 bytes

### ISSUE THREAD

**Issue by ezfox** [lyusupov/SoftRF#78]
While following https://github.com/lyusupov/SoftRF/wiki/Retro-Edition#firmware to the letter,
to compile the Retro version for BluePill with Arduino IDE 1.8.10, i get following warning & error:

Arduino: 1.8.10 (Linux), Board: "Generic STM32F1 series, BluePill F103C8 (128k), STM32CubeProgrammer (SWD), Enabled (generic 'Serial'), CDC (no generic 'Serial'), Low/Full Speed, Smallest (-Os default), Newlib Nano (default)"

**WARNING: library nRF905 claims to run on avr, esp8266, esp32 architecture(s) and may be incompatible with your current board which runs on stm32 architecture(s).**
Multiple libraries were found for "WiFiUdp.h"
 Used: /home/user/Apps/arduino-1.8.10/libraries/WiFi
Multiple libraries were found for "SrcWrapper.h"
 Used: /home/user/.arduino15/packages/STM32/hardware/stm32/1.8.0/libraries/SrcWrapper
Multiple libraries were found for "TimeLib.h"
 Used: /home/user/Arduino/libraries/Time
Multiple libraries were found for "EEPROM.h"
 Used: /home/user/.arduino15/packages/STM32/hardware/stm32/1.8.0/libraries/EEPROM
Multiple libraries were found for "Adafruit_NeoPixel.h"
 Used: /home/user/Arduino/libraries/Adafruit_NeoPixel
Multiple libraries were found for "lib_crc.h"
 Used: /home/user/Arduino/libraries/CRC
Multiple libraries were found for "uat.h"
 Used: /home/user/Arduino/libraries/dump978
Multiple libraries were found for "aircraft.h"
 Used: /home/user/Arduino/libraries/aircraft
Multiple libraries were found for "Wire.h"
**/home/user/.arduino15/packages/STM32/tools/xpack-arm-none-eabi-gcc/9.2.1-1.1/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: Retro.ino.elf section `.data' will not fit in region `FLASH'
/home/user/.arduino15/packages/STM32/tools/xpack-arm-none-eabi-gcc/9.2.1-1.1/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 268 bytes
collect2: error: ld returned 1 exit status**
 Used: /home/user/.arduino15/packages/STM32/hardware/stm32/1.8.0/libraries/Wire
Multiple libraries were found for "Adafruit_MPL3115A2.h"
 Used: /home/user/Arduino/libraries/Adafruit_MPL3115A2_Library
Multiple libraries were found for "TinyGPS++.h"
 Used: /home/user/Arduino/libraries/TinyGPSPlus
Multiple libraries were found for "ArduinoJson.h"
 Used: /home/user/Arduino/libraries/ArduinoJson
Multiple libraries were found for "IWatchdog.h"
 Used: /home/user/.arduino15/packages/STM32/hardware/stm32/1.8.0/libraries/IWatchdog
Multiple libraries were found for "adsb_encoder.h"
 Used: /home/user/Arduino/libraries/adsb_encoder
Multiple libraries were found for "lmic.h"
 Used: /home/user/Arduino/libraries/arduino-lmic
Multiple libraries were found for "mavlink.h"
 Used: /home/user/Arduino/libraries/mavlink
Multiple libraries were found for "Adafruit_BMP085.h"
 Used: /home/user/Arduino/libraries/Adafruit-BMP085-Library
Multiple libraries were found for "Adafruit_BMP280.h"
 Used: /home/user/Arduino/libraries/Adafruit_BMP280_Library
Multiple libraries were found for "SPI.h"
 Used: /home/user/.arduino15/packages/STM32/hardware/stm32/1.8.0/libraries/SPI
Multiple libraries were found for "nRF905.h"
 Used: /home/user/Arduino/libraries/nRF905
Multiple libraries were found for "egm96s.h"
 Used: /home/user/Arduino/libraries/Geoid
Multiple libraries were found for "U8x8lib.h"
 Used: /home/user/Arduino/libraries/U8g2
Multiple libraries were found for "freqplan.h"
 Used: /home/user/Arduino/libraries/OGN
**exit status 1
Error compiling for board Generic STM32F1 series.**

The more verbose output i attached here as a text file:
[verbose.txt](https://github.com/lyusupov/SoftRF/files/4108800/verbose.txt)

**Comment by lyusupov** [comment]
Report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md).

**Resolution**: invalid.
