### ISSUE TITLE
Retro STM32F1 compile error - region `FLASH' overflowed by 268 bytes

### ISSUE THREAD

**Issue by ezfox** [lyusupov/SoftRF#79]
**ATTENTION** ! 

- Use this form to report bugs in released SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are allowed only when you are ready to implement them by yourself ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder
- [X] Retro (STM32F103C8T6 & RFM95W)

< photo of your hardware > (**required**)
![photo_2020-01-24_17-33-10](https://user-images.githubusercontent.com/25694657/73085844-b25fda00-3ecf-11ea-9245-7e1fb80a2c04.jpg)

## Firmware version
STM32 1.8.0 
(https://github.com/stm32duino/Arduino_Core_STM32/releases/tag/1.8.0)

<  screenshot of WebUI status page > (**required**)
N/A (Compile Fails, so no WebUI available)

## Firmware settings
N/A

<  screenshot of WebUI settings page > (**required**)
N/A (Compile Fails, so no WebUI available)

## Describe the bug (or ask a question)
While following https://github.com/lyusupov/SoftRF/wiki/Retro-Edition#firmware to the letter,
to compile the Retro version for BluePill with Arduino IDE 1.8.10, i get following warning & error:

Arduino: 1.8.10 (Linux), Board: "Generic STM32F1 series, BluePill F103C8 (128k), STM32CubeProgrammer (SWD), Enabled (generic 'Serial'), CDC (no generic 'Serial'), Low/Full Speed, Smallest (-Os default), Newlib Nano (default)"

**WARNING: library nRF905 claims to run on avr, esp8266, esp32 architecture(s) and may be incompatible with your current board which runs on stm32 architecture(s).**
Multiple libraries were found for "WiFiUdp.h"
 Used: /home/user/Apps/arduino-1.8.10/libraries/WiFi
Multiple libraries were found for "SrcWrapper.h"
 Used: /home/user/.arduino15/packages/STM32/hardware/stm32/1.8.0/libraries/SrcWrapper
Multiple libraries were found for "TimeLib.h"
 Used: /home/user/Arduino/libraries/Time
Multiple libraries were found for "EEPROM.h"
 Used: /home/user/.arduino15/packages/STM32/hardware/stm32/1.8.0/libraries/EEPROM
Multiple libraries were found for "Adafruit_NeoPixel.h"
 Used: /home/user/Arduino/libraries/Adafruit_NeoPixel
Multiple libraries were found for "lib_crc.h"
 Used: /home/user/Arduino/libraries/CRC
Multiple libraries were found for "uat.h"
 Used: /home/user/Arduino/libraries/dump978
Multiple libraries were found for "aircraft.h"
 Used: /home/user/Arduino/libraries/aircraft
Multiple libraries were found for "Wire.h"
**/home/user/.arduino15/packages/STM32/tools/xpack-arm-none-eabi-gcc/9.2.1-1.1/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: Retro.ino.elf section `.data' will not fit in region `FLASH'
/home/user/.arduino15/packages/STM32/tools/xpack-arm-none-eabi-gcc/9.2.1-1.1/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 268 bytes
collect2: error: ld returned 1 exit status**
 Used: /home/user/.arduino15/packages/STM32/hardware/stm32/1.8.0/libraries/Wire
Multiple libraries were found for "Adafruit_MPL3115A2.h"
 Used: /home/user/Arduino/libraries/Adafruit_MPL3115A2_Library
Multiple libraries were found for "TinyGPS++.h"
 Used: /home/user/Arduino/libraries/TinyGPSPlus
Multiple libraries were found for "ArduinoJson.h"
 Used: /home/user/Arduino/libraries/ArduinoJson
Multiple libraries were found for "IWatchdog.h"
 Used: /home/user/.arduino15/packages/STM32/hardware/stm32/1.8.0/libraries/IWatchdog
Multiple libraries were found for "adsb_encoder.h"
 Used: /home/user/Arduino/libraries/adsb_encoder
Multiple libraries were found for "lmic.h"
 Used: /home/user/Arduino/libraries/arduino-lmic
Multiple libraries were found for "mavlink.h"
 Used: /home/user/Arduino/libraries/mavlink
Multiple libraries were found for "Adafruit_BMP085.h"
 Used: /home/user/Arduino/libraries/Adafruit-BMP085-Library
Multiple libraries were found for "Adafruit_BMP280.h"
 Used: /home/user/Arduino/libraries/Adafruit_BMP280_Library
Multiple libraries were found for "SPI.h"
 Used: /home/user/.arduino15/packages/STM32/hardware/stm32/1.8.0/libraries/SPI
Multiple libraries were found for "nRF905.h"
 Used: /home/user/Arduino/libraries/nRF905
Multiple libraries were found for "egm96s.h"
 Used: /home/user/Arduino/libraries/Geoid
Multiple libraries were found for "U8x8lib.h"
 Used: /home/user/Arduino/libraries/U8g2
Multiple libraries were found for "freqplan.h"
 Used: /home/user/Arduino/libraries/OGN
**exit status 1
Error compiling for board Generic STM32F1 series.**

The more verbose output i attached here as a text file:
[verbose.txt](https://github.com/lyusupov/SoftRF/files/4109510/verbose.txt)

## To Reproduce
- Follow the Guide from https://github.com/lyusupov/SoftRF/tree/master/software/firmware/source#stm32
- Watch compile process failing with above error

## Expected behavior
- Compile should finish sucessfully

**Comment by lyusupov** [comment]
Your report is generally not applicable, because:
1) issues has to be filed against [**released SoftRF firmware** source code](https://github.com/lyusupov/SoftRF/releases/tag/1.0-rc7). 
RC7 is known to be fine when built against AC/STM32 [1.7.0](https://github.com/stm32duino/Arduino_Core_STM32/releases/tag/1.7.0)
2) **I no longer process issues that comes from anonymous GitHub users**:
https://berthub.eu/articles/posts/anonymous-help/

Build of **development version** of source code is not guaranteed at any particular time, see this: https://github.com/lyusupov/SoftRF/issues/29#issuecomment-419092549

So, to save some flash memory space, either:
- build RC7 against AC 1.7.0 (or 1.6.1) , and/or
- disable USB CDC in Arduino build options, and/or
- disable pressure sensor that you don't have. Example: https://github.com/lyusupov/SoftRF/blob/master/software/firmware/source/SoftRF/Platform_STM32.h#L222

**Resolution:** invalid
