### ISSUE TITLE
can the wifi be disabled when in UAV mode?

### ISSUE THREAD

**Issue by geofrancis** [lyusupov/SoftRF#8]
can the wifi be disabled when in UAV mode as its no longer required.

**Comment by lyusupov** [comment]
Wi-Fi is the only way to change settings.
I might consider to add a menu option to self-disable Wi-Fi after boot upon few minutes of inactivity.
Or to reduce WiFi power to a bare minimum.

I will decide later.

"Wi-Fi off" has little sense to save power on UAV, but makes sense to reduce interference with flight controls/video/telemetry operating at 2.4 GHz.

**Comment by geofrancis** [comment]
its the interferance issue i am concerned about, we use a 2.4ghz video/rc link thats based on wifi so having another AP running onboard the aircraft is not an option.
