### ISSUE TITLE
Raspbery Pi with nRF905 does not transmit

### ISSUE THREAD

**Issue by sunlord2k** [lyusupov/SoftRF#80]
--------------------

## Hardware

- [ ]   Standalone
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [x ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)
![IMG_20200320_183730](https://user-images.githubusercontent.com/37815714/77190911-5a61e000-6ada-11ea-99a9-24f4180c01ac.jpg)
![IMG_20200320_183735](https://user-images.githubusercontent.com/37815714/77190932-63eb4800-6ada-11ea-9843-ec1f5e9c4b5c.jpg)

## Firmware version
latest Github Version for Raspberry (no WebUI on Raspbery)

## Firmware settings
Protocol: LEGACY
nmea:private:true for loggin purpose

## Describe the bug (or ask a question)
Setup is:
Rapbery Pi 3 with Ublox GPS and nRF905.
Pining of GPS and nRF905 correct and both are detected and SoftF is working so far.

But unfortunately the SoftRF unit is not seen by my OGN receiver.
Logs of the TCP output of the SoftRF unit attached as well as logging output of the OGN receiver.

The SoftRF Raspberry unit does receive data from other units if some are around.

Theses units (for example a T-Beam unit that i own) can be seen by the OGN receiver

I suspect that something with the implementation of the nRF905 is not correct.
And that leads to the raspberry with nRF905 not sending data. 
I checked with SDRsharp, the T-Beam sends data on 968,2 MHZ but the raspberry with nRF905 does not.

## To Reproduce
Raspberry Pi with nRF905 and a receiving unit

## Expected behavior
Raspbery Pi with nRF905 can be seen by other units and received by OGN receivers.
[OGN50000.log](https://github.com/lyusupov/SoftRF/files/4361128/OGN50000.log)
[OGN50001.log](https://github.com/lyusupov/SoftRF/files/4361129/OGN50001.log)
[softrflog-nosend2.log](https://github.com/lyusupov/SoftRF/files/4361130/softrflog-nosend2.log)

**Comment by lyusupov** [comment]
Works nicely to me:

```
$ { echo "{class:SOFTRF,mode:TEST,protocol:LEGACY,band:EU,nmea:{gnss:false,legacy:false,private:true}}" ;  } | sudo ./SoftRF

SoftRF-RPi FW.REV: 1.0-rc7 DEV.ID: D3374780
Copyright (C) 2015-2020 Linar Yusupov. All rights reserved.
NRF905 RFIC is detected.
$PSRFO,1584956909,80473720268A0D0F0F9435A135CA8B5CA52FCF49014035B1
$PSRFO,1584956910,80473720268A0D0F0F9435A135CA8B5CA52FCF49014035B1
$PSRFO,1584956911,80473720268A0D0F0F9435A135CA8B5CA52FCF49014035B1
```

```
$ telnet localhost 50001
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
@@@ Welcome to procServ (procServ Process Server 2.6.0)
@@@ Use ^X to kill the child, auto restart is ON, use ^T to toggle auto restart
@@@ Use ^C to logout from procServ server
@@@ procServ server PID: 4350
@@@ Server startup directory: /home/pi/rtlsdr-ogn-0.2.6
@@@ Child startup directory: /home/pi/rtlsdr-ogn-0.2.6
@@@ Child started as: ./ogn-decode
@@@ Child "./ogn-decode" PID: 4363
@@@ procServ server started at: Mon Mar 23 09:46:17 2020
@@@ Child "./ogn-decode" started at: Mon Mar 23 09:46:17 2020
@@@ 0 user(s) and 0 logger(s) connected (plus you)
0.804sec:868.238MHz:   1:2:374780 094832: [ +56.01396, +38.35425]deg  428m  -1.5m/s  25.5m/s 279.4deg  +0.0deg/sec 4 03x05m 00_o+38.09kHz 40.5/50.5dB/0  0e    1.5km 286.1deg +10.6deg   ?
0.520sec:868.238MHz:   1:2:374780 094833: [ +56.01437, +38.35505]deg  428m  -1.5m/s  25.5m/s 279.4deg  +0.0deg/sec 4 03x05m 00f_+38.11kHz 41.0/52.5dB/0  0e    1.5km 288.4deg +10.8deg   ?
APRS <- FLR374780>APRS,qAR:/094828h5600.83N/03821.25E'279/049/A=001404 !W74! id06374780 -296fpm +0.0rot 41.8dB 0e +38.1kHz gps3x5
0.714sec:868.238MHz:   1:2:374780 094834: [ +56.01437, +38.35505]deg  428m  -1.5m/s  25.5m/s 279.4deg  +0.0deg/sec 4 03x05m 00f_+38.13kHz 41.0/53.0dB/0  0e    1.5km 288.4deg +10.8deg   ?

```
**Tips**:

1) according to your picture attached - **your nRF905 module is likely rated to 433 MHz band only**<br>
  **RTFM:**  https://github.com/lyusupov/SoftRF/raw/master/documents/SoftRF-release-2.pdf

Known good source of 868/915 MHz nRF905 modules is this one:
https://github.com/lyusupov/SoftRF/wiki/Standalone-Modules#plug-in-modules-and-components

Even 'good' nRF905 module may have +-50 kHz frequency offset.<br>
Details:
- https://pushstack.wordpress.com/2014/07/12/controlling-the-wattcher-display/
- https://github.com/astir13/SoftRF_standalone/blob/master/documents/Crystal_Correction.pdf

<br>

2) your SPI bus wiring and soldering is horrible. Inspect that all nRF905 hardware control/data signals are properly delivered.

<br>
<br>

**Resolution:** unable to reproduce
