### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by peterlegacy** [lyusupov/SoftRF#82]
Hi, I found theese errors during compilation and now Im out of ideas how to fix it :(

In file included from sketch/SoCHelper.h:24:0,
                 from sketch/BatteryHelper.cpp:21:
SoftRF.h:113:5: error: 'time_t' does not name a type; did you mean 'size_t'?
     time_t    timestamp;

     ^~~~~~
     size_t
In file included from sketch/SoCHelper.h:24:0,
                 from sketch/BaroHelper.cpp:24:
SoftRF.h:113:5: error: 'time_t' does not name a type; did you mean 'size_t'?
     time_t    timestamp;

     ^~~~~~
     size_t
sketch/BaroHelper.cpp: In function 'bool bmp280_probe()':
BaroHelper.cpp:98:44: error: 'BME280_CHIPID' was not declared in this scope
           bmp280.begin(BMP280_ADDRESS,     BME280_CHIPID) ||

                                            ^~~~~~~~~~~~~
sketch/BaroHelper.cpp:98:44: note: suggested alternative: 'BMP280_CHIPID'
           bmp280.begin(BMP280_ADDRESS,     BME280_CHIPID) ||

                                            ^~~~~~~~~~~~~
                                            BMP280_CHIPID
In file included from sketch/D1090Helper.cpp:27:0:
TrafficHelper.h:52:28: error: 'MAX_TRACKING_OBJECTS' was not declared in this scope
 extern ufo_t fo, Container[MAX_TRACKING_OBJECTS], EmptyFO;

                            ^~~~~~~~~~~~~~~~~~~~
sketch/D1090Helper.cpp: In function 'void D1090_Out(byte*, size_t)':
D1090Helper.cpp:46:7: error: 'SerialOutput' was not declared in this scope
       SerialOutput.write(buf, size);

       ^~~~~~~~~~~~
sketch/D1090Helper.cpp:46:7: note: suggested alternative: 'Serial'
       SerialOutput.write(buf, size);

       ^~~~~~~~~~~~
       Serial
sketch/D1090Helper.cpp: In function 'void D1090_Export()':
D1090Helper.cpp:72:23: error: 'MAX_TRACKING_OBJECTS' was not declared in this scope
     for (int i=0; i < MAX_TRACKING_OBJECTS; i++) {

                       ^~~~~~~~~~~~~~~~~~~~
D1090Helper.cpp:73:11: error: 'Container' was not declared in this scope
       if (Container[i].addr && (this_moment - Container[i].timestamp) <= EXPORT_EXPIRATION_TIME) {

           ^~~~~~~~~
exit status 1
'time_t' does not name a type; did you mean 'size_t'?

**Comment by lyusupov** [comment]
Issue was filed not in compliance with [this template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) (offered automatically for each new issue).

**Resolution**: invalid.
