### ISSUE TITLE
rc8: Baro not detected

### ISSUE THREAD

**Issue by mh5151** [lyusupov/SoftRF#88]
After updating my Prime MarkII from rc7 to rc8 the Baro (BMP280) has not been detected furthermore. Status screen says Baro: NONE and XCSoar receiceves not baro data. With rc7 the BMP280 works fine.

**Comment by lyusupov** [comment]
Report is filed not in compliance with the [template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md).

**Resolution**: invalid.
