### ISSUE TITLE
Device ID (only 5 chars), too short for OGN registration

### ISSUE THREAD

**Issue by FlyingBird22** [lyusupov/SoftRF#91]
## Hardware

- [ ]   Standalone
- [x]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

![cut_TTGO](https://user-images.githubusercontent.com/69727555/90318297-f1b74c00-df2f-11ea-846b-7800e5785950.jpg)

## Firmware version

![cut_Status_marked](https://user-images.githubusercontent.com/69727555/90318391-74d8a200-df30-11ea-9d65-b0e4cf1eba18.jpg)

## Firmware settings

![cut_Settings](https://user-images.githubusercontent.com/69727555/90318403-88840880-df30-11ea-9027-afd8816843b6.jpg)

## Describe the bug (or ask a question)

Device Id has a string length of only 5 alpha numeric characters: "CEF34"
It is not possible to register an Id with only 5 characters at OGN, there is says: "Device ID format incorrect"

## To Reproduce

Don't know how to change this.

## Expected behavior

Device Id should have 6 alpha numeric characters.

**Comment by mreinart** [comment]
Q: Which ID is seen by other devices or OGN ground station receiving packets from yours? 
Q: you have trace output from console?

**Comment by FlyingBird22** [comment]
Connected to XCSoar on smartphone:

![Screenshot_20200815-204521_XCSoar](https://user-images.githubusercontent.com/69727555/90319614-f7b22a80-df39-11ea-827b-9cdd6098c514.jpg)

**Comment by lyusupov** [comment]
Report from anonymous user.
**Resolution**: invalid

**Comment by lyusupov** [comment]
Report from anonymous user.
**Resolution**: invalid

**Comment by lyusupov** [comment]
Report from anonymous user.
**Resolution**: invalid

**Comment by CazYokoyama** [comment]
It seems FlyingBird22 has a problem when he register his device on OGN Devices database, https://ddb.glidernet.org/. The device Id on SoftRF Status is reported by handleRoot() in WebHelper.cpp as 
  <tr><th align=left>Device Id</th><td align=right>%X</td></tr>\
 ThisAircraft.addr

Because of %X, the leading 0 is suppressed. For  OGN Devices database, just add 0, i.e. 0CEF34 as a temporal solution. As a  permanent solution,
"%X" should be "%06X".
I will create a pull request.

**Comment by FlyingBird22** [comment]
The good news: at OGN the number was transferred with leading 0, e.g. 0CEF34
To get better html display, at _WebHelper.cpp_ we should replace **%X** by **%.6X** in _line 597_
