### ISSUE TITLE
SoftRF Prime Edition MkII Wifi deactivation

### ISSUE THREAD

**Issue by EF2004** [lyusupov/SoftRF#95]
Is there any possibility to deactiviate Wifi for Prime Edition MkII Soft RF? Ist just want to use SoftRF as transmitter and not as a receiver. So I don't need Wifi, because I don't want interferences with other devices.

**Comment by lyusupov** [comment]
Issue was filed not in compliance with [this template](https://github.com/lyusupov/SoftRF/blob/master/.github/ISSUE_TEMPLATE/softrf-issue-template.md) (offered automatically for each new issue).

**Resolution**: invalid.

https://github.com/lyusupov/SoftRF/wiki/Settings#power-save
