### ISSUE TITLE
SoftRF Prime Edition MkII Wifi deactivation

### ISSUE THREAD

**Issue by EF2004** [lyusupov/SoftRF#96]
## Hardware

- [ ]   Standalone
- [x ]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

![TTGO_TBeam_1](https://user-images.githubusercontent.com/70629677/91958359-88915000-ed07-11ea-8180-82289bfde308.jpg)

![Unbenannt](https://user-images.githubusercontent.com/70629677/91958374-8dee9a80-ed07-11ea-9052-f9653ad80671.JPG)

![Unbenannt2](https://user-images.githubusercontent.com/70629677/91958385-90e98b00-ed07-11ea-8d0d-fae8ff3ec06f.JPG)

Is there any possibility to deactiviate Wifi for Prime Edition MkII Soft RF? Ist just want to use SoftRF as transmitter and not as a receiver. So I don't need Wifi, because I don't want interferences with other devices.

**Comment by lyusupov** [comment]
https://github.com/lyusupov/SoftRF/wiki/Settings#power-save
