### ISSUE TITLE
BME280 connected to pins 21/22 block AXP192 chip communication

### ISSUE THREAD

**Issue by OskarPepryk** [lyusupov/SoftRF#97]
## Hardware

- [ ]   Standalone
- [x]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

![obraz](https://user-images.githubusercontent.com/23101737/92157155-54fb1680-ee2a-11ea-8476-d4a2ef8e35df.png)

## Firmware version

![obraz](https://user-images.githubusercontent.com/23101737/92157205-68a67d00-ee2a-11ea-93fa-b2e91f411365.png)

## Firmware settings

![obraz](https://user-images.githubusercontent.com/23101737/92157261-79ef8980-ee2a-11ea-9b27-0e132dc430c6.png)

## Describe the bug (or ask a question)

When I connect the BME280 to pins 21/22 it is detected correctly but there is no voltage (0 volts) in status page and the device is impossible to shutdown using the soft power button.

## To Reproduce

Connect BME280 to gpio 21/22. Turn on the device. Note the incorrect voltage and that you can't turn the board off no matter how long you press the power button.

## Expected behavior

The AXP192 should continue to work. I know that the baros aren't 'officially' supported but this seems like an oversight. 

## Proposed solution

I worked out the solution. During ESP32 baro setup routine Wire was called with pins 21/22. It collides with Wire1 already running on those pins and breaks any devices (AXP192) that worked with Wire1.

I fixed this issue in [my fork ](https://github.com/OskarPepryk/SoftRF/tree/bmp280_fix) by changing BMP280 library to a newer one that supports custom Wire addresses but works with either BMP280 or BME280. I went with BME280 because that's my sensor. Unfortunately I cannot test the issue with other barometric sensors. Probably all of them need a library that can be called with Wire1.

**Comment by lyusupov** [comment]
Show me a sentence in [**Prime Mark II**](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkII) description or BOM where it is written that it has support for BME280 sensor.

Neither barometric pressure sensor nor OLED are offically supported components of [**Prime Mk II**](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkII).
Utilizing of I<sup>2</sup>C bus feature is a 'privilege' of [**Standalone Edition**](https://github.com/lyusupov/SoftRF/wiki/Standalone-Edition) & [**LoRa**](https://github.com/lyusupov/SoftRF/wiki/SoftRF-LoRa-module) builders.

So filing of an  I<sup>2</sup>C device issue onto the **Prime Mk II** is not allowed here. 

**Resolution**: invalid
