### ISSUE TITLE
40 m altitude difference between WebUI and SkyDemon

### ISSUE THREAD

**Issue by kaszika2000** [lyusupov/SoftRF#98]
**ATTENTION** ! 

- Use this form to report bugs in released SoftRF firmware, hardware and web pages only ;
- Issue reports from anonymous users will be most likely invalidated. Reasons for that are well explained [here](https://berthub.eu/articles/posts/anonymous-help/) ;
- Prior to asking a question, look into ["Closed issues"](https://github.com/lyusupov/SoftRF/issues?q=is%3Aissue+is%3Aclosed) area to see if it was answered before ;
- No any "ideas" or new feature requests, please ! New feature requests do not subject for taking into consideration unless they come from co-developers ;
- "Enhancements" of existing features are allowed only when you are ready to implement them by yourself ;

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ X]   Prime Mark II
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (**required**)
![IMG_2888](https://user-images.githubusercontent.com/65864327/93338637-dd19ec80-f82a-11ea-8a4e-edddc576b945.JPG)

## Firmware version
![IMG_2886](https://user-images.githubusercontent.com/65864327/93340051-9e853180-f82c-11ea-8752-c35157de0c2a.JPEG)

<  screenshot of WebUI status page > (**required**)

## Firmware settings

<  screenshot of WebUI settings page > (**required**)
![IMG_2887](https://user-images.githubusercontent.com/65864327/93340104-aba22080-f82c-11ea-9b08-b492d82bc9bb.JPEG)

## Describe the bug (or ask a question)
There is 40m altitude difference between displayed on the WebUI status page and displayed on SkyDemon app.
![IMG_2885](https://user-images.githubusercontent.com/65864327/93340257-e2783680-f82c-11ea-8b04-78304e884b1e.JPEG)
The value displayed on WebUI page as MSL is the correct one.

**Comment by lyusupov** [comment]
Duplicates https://github.com/lyusupov/SoftRF/issues/31

**Resolution:** duplicate
