### ISSUE TITLE
ESP8266 broken in UAV mode with RC8

### ISSUE THREAD

**Issue by Hasi123** [lyusupov/SoftRF#99]
## Hardware

- [ ]   Standalone
- [ ]   Prime Mark II
- [ ]   Uni
- [ ]   Dongle
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [X]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

## Hardware version
NodeMCU with SoftRF radio

![IMG_20200925_095215](https://user-images.githubusercontent.com/13320790/94241927-9c4e6180-ff15-11ea-8bbe-b579e0166120.jpg)

## Firmware version

![Screenshot_2020-09-25-09-53-05-798_com android chrome](https://user-images.githubusercontent.com/13320790/94241964-a8d2ba00-ff15-11ea-8855-40d1ab8eed18.jpg)

## Firmware settings

![Screenshot_2020-09-25-09-53-26-973_com android chrome](https://user-images.githubusercontent.com/13320790/94241985-b0925e80-ff15-11ea-9290-d4085ea0d6e5.jpg)

## Describe the bug (or ask a question)
With firmware versions over RC2, the tracker stops working after selecting UAV mode in the WebUI and rebooting. After this it is not even possible to connect to wifi and access the WebUI.

update. Problem only happens with ESP8266 and RC8 wirmware in UAV mode.

## To Reproduce
Connect to the device and select UAV mode in the WebUI.

## Expected behavior
Not to crash

**Comment by Hasi123** [comment]
Ok, it seems, that RC7 also works with my setup, only RC8 crashes, when UAV mode is selected.

**Comment by Hasi123** [comment]
Update 2: RC8 works with ESP32 in UAV mode. The problem only exists with ESPESP8266.

**Comment by lyusupov** [comment]
**Resolution:** fixed in https://github.com/lyusupov/SoftRF/commit/2e3ac3a308777571ced53687769faea292fe40c0
